# Pandas (1)

__Авторы задач: Блохин Н.В. (NVBlokhin@fa.ru), Макрушин С.В. (SVMakrushin@fa.ru)__

Материалы:
* Макрушин С.В. "Лекция 2: Библиотека Pandas"
* https://pandas.pydata.org/docs/user_guide/index.html#
* https://pandas.pydata.org/docs/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

1. Загрузите данные из файла `sp500hst.txt` и обозначьте столбцы в соответствии с содержимым: `"date", "ticker", "open", "high", "low", "close", "volume"`.

2. Рассчитайте среднее значение показателей для каждого из столбцов c номерами 3-6.

3. Добавьте столбец, содержащий только число месяца, к которому относится дата.

## Лабораторная работа №2.1

### Базовые операции с `DataFrame`

1.1 В файлах `recipes_sample.csv` и `reviews_sample.csv` находится информация об рецептах блюд и отзывах на эти рецепты соответственно. Загрузите данные из файлов в виде `pd.DataFrame` с названиями `recipes` и `reviews`. Обратите внимание на корректное считывание столбца с индексами в таблице `reviews` (безымянный столбец).

In [1]:
import pandas as pd

In [2]:
recipes = pd.read_csv("02_pandas_data/recipes_sample.csv")
reviews = pd.read_csv("02_pandas_data/reviews_sample.csv", index_col=0) #index_col=0 - первый столбец - индекс

In [3]:
recipes.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN

In [4]:
reviews.head()

,user_id,recipe_id,date,rating,review
370476,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
624300,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...
187037,400708,252013,2008-01-10,4,"Very nice breakfast HH, easy to make and yummy..."
706134,2001852463,404716,2017-12-11,5,These are a favorite for the holidays and so e...
312179,95810,129396,2008-03-14,5,Excellent soup! The tomato flavor is just gre...

1.2 Для каждой из таблиц выведите основные параметры:
* количество точек данных (строк);
* количество столбцов;
* тип данных каждого столбца.

In [5]:
recipes.shape[0], recipes.shape[1], recipes.dtypes

(30000,
 8,
 name               object
 id                  int64
 minutes             int64
 contributor_id      int64
 submitted          object
 n_steps           float64
 description        object
 n_ingredients     float64
 dtype: object)

In [6]:
reviews.shape[0], reviews.shape[1], reviews.dtypes

(126696,
 5,
 user_id       int64
 recipe_id     int64
 date         object
 rating        int64
 review       object
 dtype: object)

1.3 Исследуйте, в каких столбцах таблиц содержатся пропуски. Посчитайте долю строк, содержащих пропуски, в отношении к общему количеству строк.

In [7]:
recipes.isna()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,False,False,False,False,False,True,False,False
1,False,False,False,False,False,True,False,True
2,False,False,False,False,False,True,False,False
3,False,False,False,False,False,True,False,True
4,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...
29995,False,False,False,False,False,False,False,False
29996,False,False,False,False,False,True,False,False
29997,False,False,False,False,False,True,False,True
29998,False,False,False,False,False,True,False,True
29999,False,False,False,False,False,False,False,False

In [8]:
recipes.isna().sum() / recipes.shape[0]

name              0.000000
id                0.000000
minutes           0.000000
contributor_id    0.000000
submitted         0.000000
n_steps           0.373000
description       0.020767
n_ingredients     0.296000
dtype: float64

In [9]:
reviews.isna()

         user_id  recipe_id   date  rating  review
370476     False      False  False   False   False
624300     False      False  False   False   False
187037     False      False  False   False   False
706134     False      False  False   False   False
312179     False      False  False   False   False
...          ...        ...    ...     ...     ...
1013457    False      False  False   False   False
158736     False      False  False   False   False
1059834    False      False  False   False   False
453285     False      False  False   False   False
691207     False      False  False   False   False

[126696 rows x 5 columns]

In [10]:
reviews.isna().sum() / reviews.shape[0]

user_id      0.000000
recipe_id    0.000000
date         0.000000
rating       0.000000
review       0.000134
dtype: float64

1.4 Рассчитайте и выведите на экран среднее значение для каждого из числовых столбцов (где это имеет смысл).

In [11]:
recipes.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN

In [12]:
mean_recipes = recipes.mean()
mean_recipes

/Users/elena/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

id                2.218793e+05
minutes           1.233581e+02
contributor_id    5.635901e+06
n_steps           9.805582e+00
n_ingredients     9.008286e+00
dtype: float64

In [13]:
mean_reviews = reviews.mean()
mean_reviews

/Users/elena/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

user_id      1.408013e+08
recipe_id    1.600944e+05
rating       4.410802e+00
dtype: float64

1.5 Создайте и выведите на экран серию из 10 случайных названий рецептов.

In [14]:
import random
series = pd.Series([random.choice(recipes['name']) for i in range(10)])
series

0    christine s stuffed bell pepper soup
1      palo verde s green chile cornbread
2            tex mex  infused skewers   6
3                   celery root remoulade
4     snowman sugar cookies with frosting
5                 three pea chicken salad
6                       bacon tomato cups
7              low carb mozzarella sticks
8                      christmas crackers
9              middle eastern edamame dip
dtype: object

1.6 Выведите на экран строку с __номером__ `54200`. Выведите на экран строку с __индексом__ `54200`.

1.7 Измените индекс в таблице `reviews`, пронумеровав строки, начиная с нуля.

In [19]:
reviews.index = range(reviews.shape[0])
reviews.head()

,user_id,recipe_id,date,rating,review
0,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
1,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...
2,400708,252013,2008-01-10,4,"Very nice breakfast HH, easy to make and yummy..."
3,2001852463,404716,2017-12-11,5,These are a favorite for the holidays and so e...
4,95810,129396,2008-03-14,5,Excellent soup! The tomato flavor is just gre...

1.8 Выведите информацию о рецептах, время выполнения которых не больше 20 минут и кол-во ингредиентов в которых не больше 5.

In [22]:
recipes_under_20 = recipes[(recipes['minutes']<=20) & (recipes['n_ingredients']<=5)]
recipes_under_20.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
28,quick biscuit bread,302399,20,213909,2008-05-06,11.0,this is a wonderful quick bread to make as an ...,5.0
60,peas fit for a king or queen,303944,20,213909,2008-05-16,NaN,this recipe is so simple and the flavors are s...,5.0
90,hawaiian sunrise mimosa,100837,5,58104,2004-09-29,4.0,pineapple mimosa was changed to hawaiian sunri...,3.0
91,tasty dish s banana pudding in 2 minutes,286484,2,47892,2008-02-13,NaN,"""mmmm, i love bananas!"" a --tasty dish-- origi...",4.0
94,1 minute meatballs,11361,13,4470,2001-09-03,NaN,this is a real short cut for cooks in a hurry....,2.0

### Работа с датами в `pandas`

2.1 Преобразуйте столбец `submitted` из таблицы `recipes` в формат времени. Модифицируйте решение задачи 1.1 так, чтобы считать столбец сразу в нужном формате.

In [25]:
recipes = pd.read_csv("02_pandas_data/recipes_sample.csv", parse_dates=['submitted'])
recipes.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN

2.2 Выведите информацию о рецептах, добавленных в датасет не позже 2010 года.

In [26]:
recipes_2010 = recipes[recipes['submitted'].dt.year <= 2010]
recipes_2010.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN

### Работа со строковыми данными в `pandas`

3.1  Добавьте в таблицу `recipes` столбец `description_length`, в котором хранится длина описания рецепта из столбца `description`.

In [29]:
description_length = recipes['description'].str.len()
recipes['description_length'] = description_length
recipes.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0

3.2 Измените название каждого рецепта в таблице `recipes` таким образом, чтобы каждое слово в названии начиналось с прописной буквы.

In [30]:
recipes['name'] = recipes['name'].str.title()
recipes.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length
0,George S At The Cove Black Bean Soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0
1,Healthy For Them Yogurt Popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0
2,I Can T Believe It S Spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0
3,Italian Gut Busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0
4,Love Is In The Air Beef Fondue Sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0

3.3 Добавьте в таблицу `recipes` столбец `name_word_count`, в котором хранится количество слов из названии рецепта (считайте, что слова в названии разделяются только пробелами). Обратите внимание, что между словами может располагаться несколько пробелов подряд.

In [31]:
recipes['name_word_count'] = recipes['name'].str.split().str.len()
recipes.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length,name_word_count
0,George S At The Cove Black Bean Soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0,8
1,Healthy For Them Yogurt Popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0,5
2,I Can T Believe It S Spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0,7
3,Italian Gut Busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0,3
4,Love Is In The Air Beef Fondue Sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0,8