# Форматы данных

__Авторы задач: Блохин Н.В. (NVBlokhin@fa.ru), Макрушин С.В. (SVMakrushin@fa.ru)__

Материалы:
* Макрушин С.В. "Форматы данных"
* https://docs.python.org/3/library/json.html
* https://docs.h5py.org/en/stable/
* https://www.crummy.com/software/BeautifulSoup/bs4/doc.ru/bs4ru.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

1. Вывести телефоны, содержащиеся в адресной книге `addres-book.json`

2. По данным из файла `addres-book-q.xml` сформировать список словарей с телефонами каждого из людей.

3. Создайте 2 матрицы размера 1000x1000, используя различные параметризируемые распределения из numpy (https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html#distributions)

После этого сохраните получившиеся матрицы в hdf5-файл в виде двух различных датасетов. В качестве описания каждого датасета укажите параметры используемых распределений

## Лабораторная работа №3

### JSON

1.1 Считайте файл `contributors_sample.json`, воспользовавшись модулем `json` и свяжите загруженные данные с переменной `contributors`. Выведите на экран уникальные почтовые домены, содержащиеся в почтовых адресах людей. Под доменом понимается часть адреса, следующая за символом `@`.

In [1]:
import json

In [2]:
with open('03_data_files_data/contributors_sample.json') as json_file:
    contributors = json.load(json_file)

In [3]:
contributors

[{'username': 'uhebert',
  'name': 'Lindsey Nguyen',
  'sex': 'F',
  'address': '01261 Cameron Spring\nTaylorfurt, AK 97791',
  'mail': 'jsalazar@gmail.com',
  'jobs': ['Energy engineer',
   'Engineer, site',
   'Environmental health practitioner',
   'Biomedical scientist',
   'Jewellery designer'],
  'id': 35193},
 {'username': 'vickitaylor',
  'name': 'Cheryl Lewis',
  'sex': 'F',
  'address': '66992 Welch Brooks\nMarshallshire, ID 56004',
  'mail': 'bhudson@gmail.com',
  'jobs': ['Music therapist',
   'Volunteer coordinator',
   'Designer, interior/spatial'],
  'id': 91970},
 {'username': 'sheilaadams',
  'name': 'Julia Allen',
  'sex': 'F',
  'address': 'Unit 1632 Box 2971\nDPO AE 23297',
  'mail': 'darren44@yahoo.com',
  'jobs': ['Management consultant',
   'Engineer, structural',
   'Lecturer, higher education',
   'Theatre manager',
   'Designer, textile'],
  'id': 1848091},
 {'username': 'nicole82',
  'name': 'Gina Stevens',
  'sex': 'F',
  'address': '9880 Michelle Bridge\nNew Kimberlybury, WY 02583',
  'mail': 'stevensonsarah@hotmail.com',
  'jobs': ['Mechanical engineer', 'Retail banker', 'Barrister'],
  'id': 50969},
 {'username': 'jean67',
  'name': 'Nicholas Harrington',
  'sex': 'M',
  'address': '9080 Monica Crescent Suite 820\nNorth Deanbury, HI 28977',
  'mail': 'denise42@gmail.com',
  'jobs': ['Network engineer',
   'Youth worker',
   'Primary school teacher',
   'Engineer, broadcasting (operations)'],
  'id': 676820},
 {'username': 'james67',
  'name': 'Allison Gomez',
  'sex': 'F',
  'address': '635 Kenneth Ways Suite 172\nHancockfort, AZ 50544',
  'mail': 'monique02@hotmail.com',
  'jobs': ['Designer, ceramics/pottery',
   'Engineer, energy',
   'Engineer, manufacturing'],
  'id': 64918},
 {'username': 'woodmarissa',
  'name': 'Michael Jackson',
  'sex': 'M',
  'address': '4531 Phillips Underpass\nMartinezport, MA 82685',
  'mail': 'dustin32@hotmail.com',
  'jobs': ['Designer, furniture',
   'Designer, furniture',
   'Lecturer, higher education'],
  'id': 113941},
 {'username': 'sampsontammy',
  'name': 'David Cruz',
  'sex': 'M',
  'address': '81737 Amy Grove Apt. 471\nJoannaport, IA 95575',
  'mail': 'josephpowell@gmail.com',
  'jobs': ['Sport and exercise psychologist',
   'Hospital pharmacist',
   'Surveyor, minerals',
   'Geochemist',
   'Restaurant manager'],
  'id': 398160},
 {'username': 'jonathan18',
  'name': 'Mr. Matthew Robinson',
  'sex': 'M',
  'address': '01262 Dunn Ranch Apt. 256\nWest Jay, CO 99010',
  'mail': 'oclark@hotmail.com',
  'jobs': ['Clinical psychologist',
   'Retail banker',
   'Sports development officer',
   'Firefighter',
   'Charity fundraiser'],
  'id': 35635},
 {'username': 'michael53',
  'name': 'Michael Kelly',
  'sex': 'M',
  'address': '75339 Jeremy Ford\nVictoriamouth, WV 22856',
  'mail': 'danielsjessica@gmail.com',
  'jobs': ['Insurance underwriter',
   'Analytical chemist',
   'Holiday representative'],
  'id': 718054},
 {'username': 'mcmahondavid',
  'name': 'Christina Cowan',
  'sex': 'F',
  'address': '3829 Scott Prairie Apt. 614\nLoweland, CA 60640',
  'mail': 'tinabrown@gmail.com',
  'jobs': ['Network engineer',
   'Scientist, research (physical sciences)',
   'Financial planner'],
  'id': 817632},
 {'username': 'thomas96',
  'name': 'Laura Trujillo',
  'sex': 'F',
  'address': '2573 Mahoney Shore Suite 323\nWest Briannaside, FL 13733',
  'mail': 'patrickrodgers@gmail.com',
  'jobs': ['Psychiatric nurse',
   'Audiological scientist',
   'Programmer, applications',
   'Phytotherapist',
   'Records manager'],
  'id': 2406227},
 {'username': 'martindonald',
  'name': 'Diane Bell',
  'sex': 'F',
  'address': '565 Vazquez Spurs\nNew Richard, IA 19952',
  'mail': 'makayla88@hotmail.com',
  'jobs': ['Secondary school teacher',
   'Futures trader',
   'Programmer, multimedia',
   'Public affairs consultant'],
  'id': 239808},
 {'username': 'ljohnson',
  'name': 'Stephen Hull',
  'sex': 'M',
  'address': '9821 Patton Roads\nPort Scott, OH 39878',
  'mail': 'jonescrystal@hotmail.com',
  'jobs': ['Therapeutic radiographer', 'IT trainer', 'Location manager'],
  'id': 66448},
 {'username': 'wendycross',
  'name': 'William Morris',
  'sex': 'M',
  'address': '97846 Stephens Ford\nWest Mary, DC 76913',
  'mail': 'joseph72@yahoo.com',
  'jobs': ['Production engineer',
   'Chief Operating Officer',
   'Hospital doctor',
   'Radiation protection practitioner'],
  'id': 27643},
 {'username': 'wsmith',
  'name': 'Matthew Ewing',
  'sex': 'M',
  'address': '1436 Wilson Stream Suite 801\nIantown, IL 27715',
  'mail': 'ymorgan@gmail.com',
  'jobs': ['Printmaker',
   'Publishing copy',
   'Research scientist (life sciences)'],
  'id': 797706},
 {'username': 'ashlee22',
  'name': 'Dylan Rodriguez',
  'sex': 'M',
  'address': '8542 Navarro Ports\nTravisborough, SD 62180',
  'mail': 'andersonrobert@gmail.com',
  'jobs': ['Chief Technology Officer',
   'Call centre manager',
   'Chief Executive Officer',
   'Purchasing manager'],
  'id': 40493},
 {'username': 'swoodward',
  'name': 'David Brown',
  'sex': 'M',
  'address': '9359 Snyder Creek\nBruceview, SD 54485',
  'mail': 'bonnie99@hotmail.com',
  'jobs': ['Engineer, petroleum',
   'Social researcher',
   'Publishing rights manager'],
  'id': 727055},
 {'username': 'donald28',
  'name': 'Taylor Byrd',
  'sex': 'M',
  'address': '16804 Terry Wall\nPort Haileyville, WY 58276',
  'mail': 'kimberly45@yahoo.com',
  'jobs': ['Tax adviser',
   'Customer service manager',
   'Forensic psychologist',
   'Financial adviser',
   'Photographer'],
  'id': 1292969},
 {'username': 'moodydavid',
  'name': 'John Morton',
  'sex': 'M',
  'address': '408 Townsend Island Apt. 258\nPaulashire, GA 79680',
  'mail': 'ericdavis@hotmail.com',
  'jobs': ['Health and safety adviser',
   'Product/process development scientist',
   'Ceramics designer',
   'Secretary/administrator',
   'Patent attorney'],
  'id': 31364},
 {'username': 'edwardszachary',
  'name': 'Rachel Newman',
  'sex': 'F',
  'address': '847 Brian Park Apt. 089\nEast Michaelstad, FL 85845',
  'mail': 'xsmith@gmail.com',
  'jobs': ['Hotel manager',
   'Quantity surveyor',
   'Scientist, research (physical sciences)'],
  'id': 814629},
 {'username': 'ashley92',
  'name': 'Christopher Decker',
  'sex': 'M',
  'address': '50944 Jennifer Union Suite 411\nBrittanyfurt, OR 99825',
  'mail': 'gardnerjason@yahoo.com',
  'jobs': ['Forest/woodland manager',
   'Administrator, education',
   'Nurse, adult',
   'Multimedia programmer'],
  'id': 209747},
 {'username': 'tamara08',
  'name': 'Kelly Atkins',
  'sex': 'F',
  'address': '3641 Justin Estates Suite 613\nWest Rubenland, OH 42410',
  'mail': 'pmartinez@hotmail.com',
  'jobs': ['Civil Service fast streamer',
   'Psychologist, prison and probation services',
   'Armed forces training and education officer',
   'Glass blower/designer',
   'Pharmacist, hospital'],
  'id': 37636},
 {'username': 'richardsstephen',
  'name': 'Jordan Pittman',
  'sex': 'M',
  'address': '268 Richard Club\nNew Jasonland, MA 43402',
  'mail': 'kochmichael@hotmail.com',
  'jobs': ['Holiday representative',
   'Warehouse manager',
   'Psychologist, counselling',
   'Pensions consultant'],
  'id': 13483},
 {'username': 'davidreynolds',
  'name': 'Jerry Salazar',
  'sex': 'M',
  'address': '627 Mason Mill Apt. 896\nDonaldtown, LA 85040',
  'mail': 'skane@yahoo.com',
  'jobs': ['Trade mark attorney',
   'Psychotherapist, child',
   'Engineer, energy',
   'Bonds trader',
   'Journalist, broadcasting'],
  'id': 21752},
 {'username': 'nburnett',
  'name': 'Heather Larson',
  'sex': 'F',
  'address': '236 Hernandez Vista\nAnthonyberg, MI 51576',
  'mail': 'robert58@hotmail.com',
  'jobs': ['Advice worker', 'Geologist, wellsite', 'Toxicologist'],
  'id': 29291},
 {'username': 'kimberly63',
  'name': 'Adam Atkinson',
  'sex': 'M',
  'address': '27804 David Pine\nDeannashire, OH 45920',
  'mail': 'perrylaura@hotmail.com',
  'jobs': ['Media buyer',
   'Engineer, civil (consulting)',
   'Corporate treasurer'],
  'id': 424680},
 {'username': 'lindsey03',
  'name': 'William Bennett',
  'sex': 'M',
  'address': '7707 Miller Locks Suite 144\nGlennchester, GA 21253',
  'mail': 'keith76@yahoo.com',
  'jobs': ['Nature conservation officer',
   'Neurosurgeon',
   'Special effects artist',
   'Professor Emeritus',
   'Rural practice surveyor'],
  'id': 166642},
 {'username': 'patrick77',
  'name': 'John Bender',
  'sex': 'M',
  'address': '158 Oconnell Hollow\nJasonville, CA 51906',
  'mail': 'donna95@yahoo.com',
  'jobs': ['Education administrator', 'Arboriculturist', 'Facilities manager'],
  'id': 29782},
 {'username': 'christine79',
  'name': 'Kenneth Love',
  'sex': 'M',
  'address': 'Unit 4345 Box 3747\nDPO AP 52811',
  'mail': 'carrmichael@yahoo.com',
  'jobs': ['Water engineer', 'Cabin crew', 'Radiographer, diagnostic'],
  'id': 891449},
 {'username': 'beanangela',
  'name': 'Anthony Wilson',
  'sex': 'M',
  'address': '9677 Franco Camp\nEast Matthewport, KS 01648',
  'mail': 'myoung@hotmail.com',
  'jobs': ['Chief Operating Officer',
   'Chemist, analytical',
   'Engineer, civil (consulting)',
   'Product/process development scientist',
   'Osteopath'],
  'id': 167849},
 {'username': 'johnsonashley',
  'name': 'Denise Dixon',
  'sex': 'F',
  'address': '115 Brady Port Apt. 682\nSandyside, VT 54365',
  'mail': 'williamsmichelle@yahoo.com',
  'jobs': ['Insurance claims handler',
   'Quality manager',
   'Designer, exhibition/display',
   'Sub',
   'Records manager'],
  'id': 1926889},
 {'username': 'alexander89',
  'name': 'Kaitlin Lopez',
  'sex': 'F',
  'address': '3885 Derek River Suite 436\nNew Debraville, TX 56047',
  'mail': 'angela69@yahoo.com',
  'jobs': ['Market researcher',
   'Colour technologist',
   'Emergency planning/management officer'],
  'id': 47892},
 {'username': 'vincent02',
  'name': 'Rebecca Casey',
  'sex': 'F',
  'address': '92862 Zachary Forge Apt. 896\nEricksonmouth, VA 70050',
  'mail': 'riosrichard@hotmail.com',
  'jobs': ['Lexicographer', 'Hospital doctor', 'Water quality scientist'],
  'id': 47549},
 {'username': 'lopezantonio',
  'name': 'Adam Watson',
  'sex': 'M',
  'address': '90456 Justin Wells Apt. 266\nStacyberg, FL 37938',
  'mail': 'lauren19@hotmail.com',
  'jobs': ['Engineer, water',
   'Jewellery designer',
   'Surveyor, insurance',
   'Environmental manager'],
  'id': 454149},
 {'username': 'powersemily',
  'name': 'Stacy Wood',
  'sex': 'F',
  'address': '6862 Eric Shoal Apt. 336\nNew Sheila, IL 41723',
  'mail': 'tmiller@yahoo.com',
  'jobs': ['Maintenance engineer',
   'Charity fundraiser',
   "Nurse, children's",
   'Astronomer'],
  'id': 1299206},
 {'username': 'joseconley',
  'name': 'Brooke Higgins',
  'sex': 'F',
  'address': '71018 Henson Mews\nGregoryhaven, ME 68359',
  'mail': 'cummingsjared@gmail.com',
  'jobs': ['Archaeologist',
   'Journalist, newspaper',
   'Accountant, chartered',
   'Computer games developer'],
  'id': 498271},
 {'username': 'leslie69',
  'name': 'Olivia Johnson',
  'sex': 'F',
  'address': '6878 James Tunnel Apt. 770\nWest Keith, IL 97125',
  'mail': 'jamie80@yahoo.com',
  'jobs': ['Drilling engineer',
   'Scientist, research (physical sciences)',
   'Environmental manager',
   'Librarian, academic',
   'Biomedical engineer'],
  'id': 37449},
 {'username': 'james03',
  'name': 'Alison Smith',
  'sex': 'F',
  'address': '87793 Livingston Estate Apt. 513\nNew Rachel, NY 40946',
  'mail': 'kerri43@gmail.com',
  'jobs': ['Psychologist, prison and probation services',
   'Haematologist',
   'Presenter, broadcasting'],
  'id': 1375473},
 {'username': 'calhounchristopher',
  'name': 'Juan Miller',
  'sex': 'M',
  'address': '044 Johnny Track Apt. 543\nKathrynview, ID 67020',
  'mail': 'alexanderdouglas@yahoo.com',
  'jobs': ['Lexicographer',
   'Surveyor, commercial/residential',
   'Engineer, electronics'],
  'id': 2247203},
 {'username': 'wgray',
  'name': 'Patrick Johnson',
  'sex': 'M',
  'address': 'Unit 0962 Box 0438\nDPO AA 87836',
  'mail': 'uchavez@gmail.com',
  'jobs': ['Maintenance engineer',
   'Surveyor, land/geomatics',
   'Accountant, chartered management'],
  'id': 94189},
 {'username': 'laura87',
  'name': 'Justin Barron',
  'sex': 'M',
  'address': '6288 Franklin Villages Suite 093\nNorth Elizabeth, VA 76953',
  'mail': 'renee68@hotmail.com',
  'jobs': ['Broadcast engineer',
   'Engineer, building services',
   'Patent examiner',
   'Media planner'],
  'id': 279496},
 {'username': 'bethany97',
  'name': 'David Kirk',
  'sex': 'M',
  'address': '722 Jennifer Estates Suite 046\nPort Kennethfurt, GA 36698',
  'mail': 'vgonzalez@hotmail.com',
  'jobs': ['Ecologist',
   'Astronomer',
   'Chief Operating Officer',
   'Geographical information systems officer',
   'Paramedic'],
  'id': 57042},
 {'username': 'tyroneglass',
  'name': 'Sydney Cisneros',
  'sex': 'F',
  'address': '1276 Katie Stream Suite 648\nDouglasburgh, HI 24784',
  'mail': 'toddgarcia@hotmail.com',
  'jobs': ['Designer, television/film set',
   'Public librarian',
   'Petroleum engineer',
   'Cabin crew',
   'Sales professional, IT'],
  'id': 205983},
 {'username': 'blanchardjackie',
  'name': 'Blake Fletcher',
  'sex': 'M',
  'address': '7744 Ray Way Apt. 856\nNew Ray, SD 70899',
  'mail': 'clarkkrista@hotmail.com',
  'jobs': ['Clinical molecular geneticist',
   'Commercial art gallery manager',
   'Scientist, research (physical sciences)'],
  'id': 379836},
 {'username': 'annmoore',
  'name': 'Richard Brown',
  'sex': 'M',
  'address': '5793 Hart Unions\nWest Tonyville, WA 85226',
  'mail': 'briankennedy@yahoo.com',
  'jobs': ['Energy engineer',
   'Television/film/video producer',
   'Dispensing optician',
   'Buyer, industrial',
   'Energy manager'],
  'id': 210965},
 {'username': 'wwinters',
  'name': 'Crystal Blair',
  'sex': 'F',
  'address': '1434 Matthew Locks\nKeithmouth, IL 03520',
  'mail': 'flopez@gmail.com',
  'jobs': ['Publishing copy', 'Ecologist', 'Structural engineer'],
  'id': 126687},
 {'username': 'richard91',
  'name': 'Kenneth Wright',
  'sex': 'M',
  'address': '22129 Donna Coves\nLake Douglasside, NJ 54596',
  'mail': 'ronald61@gmail.com',
  'jobs': ['Chief Strategy Officer',
   'Building control surveyor',
   'Product designer'],
  'id': 63855},
 {'username': 'christina73',
  'name': 'Karina Miller',
  'sex': 'F',
  'address': 'USCGC Stanley\nFPO AP 62480',
  'mail': 'anthony91@yahoo.com',
  'jobs': ['Archaeologist',
   'Analytical chemist',
   'Surveyor, planning and development',
   'Architect'],
  'id': 189030},
 {'username': 'zmartin',
  'name': 'Kyle Harrison',
  'sex': 'M',
  'address': '35728 George Harbors\nPalmerhaven, NY 19496',
  'mail': 'kfoster@gmail.com',
  'jobs': ['Social researcher', 'Dietitian', 'Engineer, chemical'],
  'id': 524879},
 {'username': 'richard14',
  'name': 'Carla Miller',
  'sex': 'F',
  'address': '0975 Patton Points Suite 520\nGutierrezburgh, MI 89035',
  'mail': 'jermaine23@yahoo.com',
  'jobs': ['Transport planner',
   'Radiographer, diagnostic',
   'Therapist, sports',
   'Facilities manager'],
  'id': 470110},
 {'username': 'amy62',
  'name': 'Nicole Smith',
  'sex': 'F',
  'address': '798 Torres Circles\nComptonmouth, AL 88224',
  'mail': 'fcharles@hotmail.com',
  'jobs': ['Scientist, audiological',
   'Learning mentor',
   'Air broker',
   'Oceanographer'],
  'id': 131674},
 {'username': 'sstrickland',
  'name': 'Sandra Clark',
  'sex': 'F',
  'address': '909 William Springs Apt. 438\nRhondaport, WY 17145',
  'mail': 'chavezrobert@yahoo.com',
  'jobs': ['Psychotherapist, dance movement',
   'Physicist, medical',
   'Equities trader',
   'Radiation protection practitioner'],
  'id': 303454},
 {'username': 'icervantes',
  'name': 'Deborah Conrad',
  'sex': 'F',
  'address': '75565 Parrish Skyway Apt. 904\nMurphyhaven, OR 23100',
  'mail': 'maldonadocourtney@yahoo.com',
  'jobs': ['Dance movement psychotherapist',
   'Theatre manager',
   'Electrical engineer',
   'Site engineer'],
  'id': 1618462},
 {'username': 'ydavis',
  'name': 'Judith Richardson',
  'sex': 'F',
  'address': '027 Pamela Parkway Suite 059\nWhiteton, WV 30405',
  'mail': 'turnerkathryn@hotmail.com',
  'jobs': ['Phytotherapist',
   'Occupational psychologist',
   'Librarian, academic',
   'Physicist, medical',
   'Merchandiser, retail'],
  'id': 789314},
 {'username': 'luceroashley',
  'name': 'Molly Mooney',
  'sex': 'F',
  'address': '6371 Robert Corners\nEast Michaelland, ND 55885',
  'mail': 'lharrington@gmail.com',
  'jobs': ['Planning and development surveyor',
   'Environmental education officer',
   'Arts development officer',
   'Surveyor, land/geomatics'],
  'id': 205783},
 {'username': 'mariaporter',
  'name': 'Michael Johnson',
  'sex': 'M',
  'address': '65191 Sarah Islands Apt. 215\nLisaborough, VA 81648',
  'mail': 'davidshah@yahoo.com',
  'jobs': ['Horticultural therapist',
   'Recruitment consultant',
   'Financial planner',
   'Energy manager',
   'Editor, magazine features'],
  'id': 63098},
 {'username': 'kristen66',
  'name': 'Christy Jones DDS',
  'sex': 'F',
  'address': '9705 Christopher Crossing\nNew Matthewland, ND 15813',
  'mail': 'carlareed@yahoo.com',
  'jobs': ['Nature conservation officer',
   'Scientist, forensic',
   'Geologist, engineering'],
  'id': 193516},
 {'username': 'nunezjeffrey',
  'name': 'Albert Richards',
  'sex': 'M',
  'address': '056 Davis Ways Apt. 530\nNicolebury, OK 84769',
  'mail': 'ncox@gmail.com',
  'jobs': ['Architect',
   'IT sales professional',
   'Psychologist, educational',
   'Risk analyst'],
  'id': 107135},
 {'username': 'rwilliams',
  'name': 'Alexandria Myers',
  'sex': 'F',
  'address': 'USNS Hanson\nFPO AE 27071',
  'mail': 'thomasmary@yahoo.com',
  'jobs': ['Scientist, research (life sciences)',
   'Designer, exhibition/display',
   'Technical sales engineer'],
  'id': 613457},
 {'username': 'hmata',
  'name': 'Crystal Parks',
  'sex': 'F',
  'address': '947 Michael Heights\nBrowntown, WI 08542',
  'mail': 'ronald80@yahoo.com',
  'jobs': ['Haematologist',
   'Insurance claims handler',
   'Restaurant manager',
   'Publishing copy',
   'Network engineer'],
  'id': 69474},
 {'username': 'davidsondouglas',
  'name': 'Jennifer Hicks',
  'sex': 'F',
  'address': '101 Dominguez Overpass Apt. 644\nNew Linda, WY 27449',
  'mail': 'stuartjackson@hotmail.com',
  'jobs': ['Adult nurse',
   'Animal nutritionist',
   'English as a foreign language teacher',
   'Product/process development scientist',
   'Publishing copy'],
  'id': 6357},
 {'username': 'ocurry',
  'name': 'Ashley Stout',
  'sex': 'F',
  'address': '706 John Mountains\nLake Jennifer, OK 37366',
  'mail': 'peter52@hotmail.com',
  'jobs': ['Manufacturing systems engineer',
   'Orthoptist',
   'Financial trader',
   'Clinical cytogeneticist'],
  'id': 528468},
 {'username': 'orobles',
  'name': 'Renee Bennett',
  'sex': 'F',
  'address': '5657 Green Corners\nTimothymouth, MO 39130',
  'mail': 'hillelizabeth@yahoo.com',
  'jobs': ['Nurse, learning disability',
   'Chief of Staff',
   'Financial planner'],
  'id': 136726},
 {'username': 'anna17',
  'name': 'Colleen Scott',
  'sex': 'F',
  'address': '0510 Anderson Orchard\nNelsonstad, KY 92537',
  'mail': 'james20@hotmail.com',
  'jobs': ['Child psychotherapist', 'Seismic interpreter', 'Retail manager'],
  'id': 37026},
 {'username': 'waltonhannah',
  'name': 'William Bernard',
  'sex': 'M',
  'address': 'PSC 2462, Box 5852\nAPO AA 43271',
  'mail': 'millergail@yahoo.com',
  'jobs': ['Logistics and distribution manager',
   'Merchant navy officer',
   'Microbiologist'],
  'id': 77146},
 {'username': 'jamesmckenzie',
  'name': 'Howard Blankenship',
  'sex': 'M',
  'address': 'PSC 1853, Box 6104\nAPO AE 61953',
  'mail': 'huntsarah@gmail.com',
  'jobs': ['Professor Emeritus',
   'Librarian, public',
   'Learning mentor',
   'Education officer, community'],
  'id': 407338},
 {'username': 'michael28',
  'name': 'Dr. Charles Jones',
  'sex': 'M',
  'address': '03999 Mckinney Stream\nWilliamsland, VT 98324',

In [4]:
domens = []
for contributor in contributors: 
    domens.append(contributor['mail'].split('@')[1])
domens = set(domens)
domens

{'gmail.com', 'hotmail.com', 'yahoo.com'}

1.2 Посчитайте, как часто встречается та или иная должность во всем наборе данных. Выведите на экран 5 должностей, которые встречаются наиболее часто. Для каждого пользователя из `contributors` выясните, какая из его должностей является наиболее распространенной (в смысле частоты упоминания во всем датасете) и добавьте ключ `top_job`, в котором хранится название этой должности.

In [5]:
jobs = {}
def get_top_job(contributor):
    for job in contributor['jobs']:
        if job in jobs:
            jobs[job] += 1
        else:
            jobs[job] = 1
    return max(jobs, key=jobs.get)

for contributor in contributors:
    contributor['top_job'] = get_top_job(contributor)

contributors

[{'username': 'uhebert',
  'name': 'Lindsey Nguyen',
  'sex': 'F',
  'address': '01261 Cameron Spring\nTaylorfurt, AK 97791',
  'mail': 'jsalazar@gmail.com',
  'jobs': ['Energy engineer',
   'Engineer, site',
   'Environmental health practitioner',
   'Biomedical scientist',
   'Jewellery designer'],
  'id': 35193,
  'top_job': 'Energy engineer'},
 {'username': 'vickitaylor',
  'name': 'Cheryl Lewis',
  'sex': 'F',
  'address': '66992 Welch Brooks\nMarshallshire, ID 56004',
  'mail': 'bhudson@gmail.com',
  'jobs': ['Music therapist',
   'Volunteer coordinator',
   'Designer, interior/spatial'],
  'id': 91970,
  'top_job': 'Energy engineer'},
 {'username': 'sheilaadams',
  'name': 'Julia Allen',
  'sex': 'F',
  'address': 'Unit 1632 Box 2971\nDPO AE 23297',
  'mail': 'darren44@yahoo.com',
  'jobs': ['Management consultant',
   'Engineer, structural',
   'Lecturer, higher education',
   'Theatre manager',
   'Designer, textile'],
  'id': 1848091,
  'top_job': 'Energy engineer'},
 {'username': 'nicole82',
  'name': 'Gina Stevens',
  'sex': 'F',
  'address': '9880 Michelle Bridge\nNew Kimberlybury, WY 02583',
  'mail': 'stevensonsarah@hotmail.com',
  'jobs': ['Mechanical engineer', 'Retail banker', 'Barrister'],
  'id': 50969,
  'top_job': 'Energy engineer'},
 {'username': 'jean67',
  'name': 'Nicholas Harrington',
  'sex': 'M',
  'address': '9080 Monica Crescent Suite 820\nNorth Deanbury, HI 28977',
  'mail': 'denise42@gmail.com',
  'jobs': ['Network engineer',
   'Youth worker',
   'Primary school teacher',
   'Engineer, broadcasting (operations)'],
  'id': 676820,
  'top_job': 'Energy engineer'},
 {'username': 'james67',
  'name': 'Allison Gomez',
  'sex': 'F',
  'address': '635 Kenneth Ways Suite 172\nHancockfort, AZ 50544',
  'mail': 'monique02@hotmail.com',
  'jobs': ['Designer, ceramics/pottery',
   'Engineer, energy',
   'Engineer, manufacturing'],
  'id': 64918,
  'top_job': 'Energy engineer'},
 {'username': 'woodmarissa',
  'name': 'Michael Jackson',
  'sex': 'M',
  'address': '4531 Phillips Underpass\nMartinezport, MA 82685',
  'mail': 'dustin32@hotmail.com',
  'jobs': ['Designer, furniture',
   'Designer, furniture',
   'Lecturer, higher education'],
  'id': 113941,
  'top_job': 'Lecturer, higher education'},
 {'username': 'sampsontammy',
  'name': 'David Cruz',
  'sex': 'M',
  'address': '81737 Amy Grove Apt. 471\nJoannaport, IA 95575',
  'mail': 'josephpowell@gmail.com',
  'jobs': ['Sport and exercise psychologist',
   'Hospital pharmacist',
   'Surveyor, minerals',
   'Geochemist',
   'Restaurant manager'],
  'id': 398160,
  'top_job': 'Lecturer, higher education'},
 {'username': 'jonathan18',
  'name': 'Mr. Matthew Robinson',
  'sex': 'M',
  'address': '01262 Dunn Ranch Apt. 256\nWest Jay, CO 99010',
  'mail': 'oclark@hotmail.com',
  'jobs': ['Clinical psychologist',
   'Retail banker',
   'Sports development officer',
   'Firefighter',
   'Charity fundraiser'],
  'id': 35635,
  'top_job': 'Lecturer, higher education'},
 {'username': 'michael53',
  'name': 'Michael Kelly',
  'sex': 'M',
  'address': '75339 Jeremy Ford\nVictoriamouth, WV 22856',
  'mail': 'danielsjessica@gmail.com',
  'jobs': ['Insurance underwriter',
   'Analytical chemist',
   'Holiday representative'],
  'id': 718054,
  'top_job': 'Lecturer, higher education'},
 {'username': 'mcmahondavid',
  'name': 'Christina Cowan',
  'sex': 'F',
  'address': '3829 Scott Prairie Apt. 614\nLoweland, CA 60640',
  'mail': 'tinabrown@gmail.com',
  'jobs': ['Network engineer',
   'Scientist, research (physical sciences)',
   'Financial planner'],
  'id': 817632,
  'top_job': 'Lecturer, higher education'},
 {'username': 'thomas96',
  'name': 'Laura Trujillo',
  'sex': 'F',
  'address': '2573 Mahoney Shore Suite 323\nWest Briannaside, FL 13733',
  'mail': 'patrickrodgers@gmail.com',
  'jobs': ['Psychiatric nurse',
   'Audiological scientist',
   'Programmer, applications',
   'Phytotherapist',
   'Records manager'],
  'id': 2406227,
  'top_job': 'Lecturer, higher education'},
 {'username': 'martindonald',
  'name': 'Diane Bell',
  'sex': 'F',
  'address': '565 Vazquez Spurs\nNew Richard, IA 19952',
  'mail': 'makayla88@hotmail.com',
  'jobs': ['Secondary school teacher',
   'Futures trader',
   'Programmer, multimedia',
   'Public affairs consultant'],
  'id': 239808,
  'top_job': 'Lecturer, higher education'},
 {'username': 'ljohnson',
  'name': 'Stephen Hull',
  'sex': 'M',
  'address': '9821 Patton Roads\nPort Scott, OH 39878',
  'mail': 'jonescrystal@hotmail.com',
  'jobs': ['Therapeutic radiographer', 'IT trainer', 'Location manager'],
  'id': 66448,
  'top_job': 'Lecturer, higher education'},
 {'username': 'wendycross',
  'name': 'William Morris',
  'sex': 'M',
  'address': '97846 Stephens Ford\nWest Mary, DC 76913',
  'mail': 'joseph72@yahoo.com',
  'jobs': ['Production engineer',
   'Chief Operating Officer',
   'Hospital doctor',
   'Radiation protection practitioner'],
  'id': 27643,
  'top_job': 'Lecturer, higher education'},
 {'username': 'wsmith',
  'name': 'Matthew Ewing',
  'sex': 'M',
  'address': '1436 Wilson Stream Suite 801\nIantown, IL 27715',
  'mail': 'ymorgan@gmail.com',
  'jobs': ['Printmaker',
   'Publishing copy',
   'Research scientist (life sciences)'],
  'id': 797706,
  'top_job': 'Lecturer, higher education'},
 {'username': 'ashlee22',
  'name': 'Dylan Rodriguez',
  'sex': 'M',
  'address': '8542 Navarro Ports\nTravisborough, SD 62180',
  'mail': 'andersonrobert@gmail.com',
  'jobs': ['Chief Technology Officer',
   'Call centre manager',
   'Chief Executive Officer',
   'Purchasing manager'],
  'id': 40493,
  'top_job': 'Lecturer, higher education'},
 {'username': 'swoodward',
  'name': 'David Brown',
  'sex': 'M',
  'address': '9359 Snyder Creek\nBruceview, SD 54485',
  'mail': 'bonnie99@hotmail.com',
  'jobs': ['Engineer, petroleum',
   'Social researcher',
   'Publishing rights manager'],
  'id': 727055,
  'top_job': 'Lecturer, higher education'},
 {'username': 'donald28',
  'name': 'Taylor Byrd',
  'sex': 'M',
  'address': '16804 Terry Wall\nPort Haileyville, WY 58276',
  'mail': 'kimberly45@yahoo.com',
  'jobs': ['Tax adviser',
   'Customer service manager',
   'Forensic psychologist',
   'Financial adviser',
   'Photographer'],
  'id': 1292969,
  'top_job': 'Lecturer, higher education'},
 {'username': 'moodydavid',
  'name': 'John Morton',
  'sex': 'M',
  'address': '408 Townsend Island Apt. 258\nPaulashire, GA 79680',
  'mail': 'ericdavis@hotmail.com',
  'jobs': ['Health and safety adviser',
   'Product/process development scientist',
   'Ceramics designer',
   'Secretary/administrator',
   'Patent attorney'],
  'id': 31364,
  'top_job': 'Lecturer, higher education'},
 {'username': 'edwardszachary',
  'name': 'Rachel Newman',
  'sex': 'F',
  'address': '847 Brian Park Apt. 089\nEast Michaelstad, FL 85845',
  'mail': 'xsmith@gmail.com',
  'jobs': ['Hotel manager',
   'Quantity surveyor',
   'Scientist, research (physical sciences)'],
  'id': 814629,
  'top_job': 'Lecturer, higher education'},
 {'username': 'ashley92',
  'name': 'Christopher Decker',
  'sex': 'M',
  'address': '50944 Jennifer Union Suite 411\nBrittanyfurt, OR 99825',
  'mail': 'gardnerjason@yahoo.com',
  'jobs': ['Forest/woodland manager',
   'Administrator, education',
   'Nurse, adult',
   'Multimedia programmer'],
  'id': 209747,
  'top_job': 'Lecturer, higher education'},
 {'username': 'tamara08',
  'name': 'Kelly Atkins',
  'sex': 'F',
  'address': '3641 Justin Estates Suite 613\nWest Rubenland, OH 42410',
  'mail': 'pmartinez@hotmail.com',
  'jobs': ['Civil Service fast streamer',
   'Psychologist, prison and probation services',
   'Armed forces training and education officer',
   'Glass blower/designer',
   'Pharmacist, hospital'],
  'id': 37636,
  'top_job': 'Lecturer, higher education'},
 {'username': 'richardsstephen',
  'name': 'Jordan Pittman',
  'sex': 'M',
  'address': '268 Richard Club\nNew Jasonland, MA 43402',
  'mail': 'kochmichael@hotmail.com',
  'jobs': ['Holiday representative',
   'Warehouse manager',
   'Psychologist, counselling',
   'Pensions consultant'],
  'id': 13483,
  'top_job': 'Lecturer, higher education'},
 {'username': 'davidreynolds',
  'name': 'Jerry Salazar',
  'sex': 'M',
  'address': '627 Mason Mill Apt. 896\nDonaldtown, LA 85040',
  'mail': 'skane@yahoo.com',
  'jobs': ['Trade mark attorney',
   'Psychotherapist, child',
   'Engineer, energy',
   'Bonds trader',
   'Journalist, broadcasting'],
  'id': 21752,
  'top_job': 'Lecturer, higher education'},
 {'username': 'nburnett',
  'name': 'Heather Larson',
  'sex': 'F',
  'address': '236 Hernandez Vista\nAnthonyberg, MI 51576',
  'mail': 'robert58@hotmail.com',
  'jobs': ['Advice worker', 'Geologist, wellsite', 'Toxicologist'],
  'id': 29291,
  'top_job': 'Lecturer, higher education'},
 {'username': 'kimberly63',
  'name': 'Adam Atkinson',
  'sex': 'M',
  'address': '27804 David Pine\nDeannashire, OH 45920',
  'mail': 'perrylaura@hotmail.com',
  'jobs': ['Media buyer',
   'Engineer, civil (consulting)',
   'Corporate treasurer'],
  'id': 424680,
  'top_job': 'Lecturer, higher education'},
 {'username': 'lindsey03',
  'name': 'William Bennett',
  'sex': 'M',
  'address': '7707 Miller Locks Suite 144\nGlennchester, GA 21253',
  'mail': 'keith76@yahoo.com',
  'jobs': ['Nature conservation officer',
   'Neurosurgeon',
   'Special effects artist',
   'Professor Emeritus',
   'Rural practice surveyor'],
  'id': 166642,
  'top_job': 'Lecturer, higher education'},
 {'username': 'patrick77',
  'name': 'John Bender',
  'sex': 'M',
  'address': '158 Oconnell Hollow\nJasonville, CA 51906',
  'mail': 'donna95@yahoo.com',
  'jobs': ['Education administrator', 'Arboriculturist', 'Facilities manager'],
  'id': 29782,
  'top_job': 'Lecturer, higher education'},
 {'username': 'christine79',
  'name': 'Kenneth Love',
  'sex': 'M',
  'address': 'Unit 4345 Box 3747\nDPO AP 52811',
  'mail': 'carrmichael@yahoo.com',
  'jobs': ['Water engineer', 'Cabin crew', 'Radiographer, diagnostic'],
  'id': 891449,
  'top_job': 'Lecturer, higher education'},
 {'username': 'beanangela',
  'name': 'Anthony Wilson',
  'sex': 'M',
  'address': '9677 Franco Camp\nEast Matthewport, KS 01648',
  'mail': 'myoung@hotmail.com',
  'jobs': ['Chief Operating Officer',
   'Chemist, analytical',
   'Engineer, civil (consulting)',
   'Product/process development scientist',
   'Osteopath'],
  'id': 167849,
  'top_job': 'Lecturer, higher education'},
 {'username': 'johnsonashley',
  'name': 'Denise Dixon',
  'sex': 'F',
  'address': '115 Brady Port Apt. 682\nSandyside, VT 54365',
  'mail': 'williamsmichelle@yahoo.com',
  'jobs': ['Insurance claims handler',
   'Quality manager',
   'Designer, exhibition/display',
   'Sub',
   'Records manager'],
  'id': 1926889,
  'top_job': 'Lecturer, higher education'},
 {'username': 'alexander89',
  'name': 'Kaitlin Lopez',
  'sex': 'F',
  'address': '3885 Derek River Suite 436\nNew Debraville, TX 56047',
  'mail': 'angela69@yahoo.com',
  'jobs': ['Market researcher',
   'Colour technologist',
   'Emergency planning/management officer'],
  'id': 47892,
  'top_job': 'Lecturer, higher education'},
 {'username': 'vincent02',
  'name': 'Rebecca Casey',
  'sex': 'F',
  'address': '92862 Zachary Forge Apt. 896\nEricksonmouth, VA 70050',
  'mail': 'riosrichard@hotmail.com',
  'jobs': ['Lexicographer', 'Hospital doctor', 'Water quality scientist'],
  'id': 47549,
  'top_job': 'Lecturer, higher education'},
 {'username': 'lopezantonio',
  'name': 'Adam Watson',
  'sex': 'M',
  'address': '90456 Justin Wells Apt. 266\nStacyberg, FL 37938',
  'mail': 'lauren19@hotmail.com',
  'jobs': ['Engineer, water',
   'Jewellery designer',
   'Surveyor, insurance',
   'Environmental manager'],
  'id': 454149,
  'top_job': 'Jewellery designer'},
 {'username': 'powersemily',
  'name': 'Stacy Wood',
  'sex': 'F',
  'address': '6862 Eric Shoal Apt. 336\nNew Sheila, IL 41723',
  'mail': 'tmiller@yahoo.com',
  'jobs': ['Maintenance engineer',
   'Charity fundraiser',
   "Nurse, children's",
   'Astronomer'],
  'id': 1299206,
  'top_job': 'Jewellery designer'},
 {'username': 'joseconley',
  'name': 'Brooke Higgins',
  'sex': 'F',
  'address': '71018 Henson Mews\nGregoryhaven, ME 68359',
  'mail': 'cummingsjared@gmail.com',
  'jobs': ['Archaeologist',
   'Journalist, newspaper',
   'Accountant, chartered',
   'Computer games developer'],
  'id': 498271,
  'top_job': 'Jewellery designer'},
 {'username': 'leslie69',
  'name': 'Olivia Johnson',
  'sex': 'F',
  'address': '6878 James Tunnel Apt. 770\nWest Keith, IL 97125',
  'mail': 'jamie80@yahoo.com',
  'jobs': ['Drilling engineer',
   'Scientist, research (physical sciences)',
   'Environmental manager',
   'Librarian, academic',
   'Biomedical engineer'],
  'id': 37449,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'james03',
  'name': 'Alison Smith',
  'sex': 'F',
  'address': '87793 Livingston Estate Apt. 513\nNew Rachel, NY 40946',
  'mail': 'kerri43@gmail.com',
  'jobs': ['Psychologist, prison and probation services',
   'Haematologist',
   'Presenter, broadcasting'],
  'id': 1375473,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'calhounchristopher',
  'name': 'Juan Miller',
  'sex': 'M',
  'address': '044 Johnny Track Apt. 543\nKathrynview, ID 67020',
  'mail': 'alexanderdouglas@yahoo.com',
  'jobs': ['Lexicographer',
   'Surveyor, commercial/residential',
   'Engineer, electronics'],
  'id': 2247203,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'wgray',
  'name': 'Patrick Johnson',
  'sex': 'M',
  'address': 'Unit 0962 Box 0438\nDPO AA 87836',
  'mail': 'uchavez@gmail.com',
  'jobs': ['Maintenance engineer',
   'Surveyor, land/geomatics',
   'Accountant, chartered management'],
  'id': 94189,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'laura87',
  'name': 'Justin Barron',
  'sex': 'M',
  'address': '6288 Franklin Villages Suite 093\nNorth Elizabeth, VA 76953',
  'mail': 'renee68@hotmail.com',
  'jobs': ['Broadcast engineer',
   'Engineer, building services',
   'Patent examiner',
   'Media planner'],
  'id': 279496,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'bethany97',
  'name': 'David Kirk',
  'sex': 'M',
  'address': '722 Jennifer Estates Suite 046\nPort Kennethfurt, GA 36698',
  'mail': 'vgonzalez@hotmail.com',
  'jobs': ['Ecologist',
   'Astronomer',
   'Chief Operating Officer',
   'Geographical information systems officer',
   'Paramedic'],
  'id': 57042,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'tyroneglass',
  'name': 'Sydney Cisneros',
  'sex': 'F',
  'address': '1276 Katie Stream Suite 648\nDouglasburgh, HI 24784',
  'mail': 'toddgarcia@hotmail.com',
  'jobs': ['Designer, television/film set',
   'Public librarian',
   'Petroleum engineer',
   'Cabin crew',
   'Sales professional, IT'],
  'id': 205983,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'blanchardjackie',
  'name': 'Blake Fletcher',
  'sex': 'M',
  'address': '7744 Ray Way Apt. 856\nNew Ray, SD 70899',
  'mail': 'clarkkrista@hotmail.com',
  'jobs': ['Clinical molecular geneticist',
   'Commercial art gallery manager',
   'Scientist, research (physical sciences)'],
  'id': 379836,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'annmoore',
  'name': 'Richard Brown',
  'sex': 'M',
  'address': '5793 Hart Unions\nWest Tonyville, WA 85226',
  'mail': 'briankennedy@yahoo.com',
  'jobs': ['Energy engineer',
   'Television/film/video producer',
   'Dispensing optician',
   'Buyer, industrial',
   'Energy manager'],
  'id': 210965,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'wwinters',
  'name': 'Crystal Blair',
  'sex': 'F',
  'address': '1434 Matthew Locks\nKeithmouth, IL 03520',
  'mail': 'flopez@gmail.com',
  'jobs': ['Publishing copy', 'Ecologist', 'Structural engineer'],
  'id': 126687,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'richard91',
  'name': 'Kenneth Wright',
  'sex': 'M',
  'address': '22129 Donna Coves\nLake Douglasside, NJ 54596',
  'mail': 'ronald61@gmail.com',
  'jobs': ['Chief Strategy Officer',
   'Building control surveyor',
   'Product designer'],
  'id': 63855,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'christina73',
  'name': 'Karina Miller',
  'sex': 'F',
  'address': 'USCGC Stanley\nFPO AP 62480',
  'mail': 'anthony91@yahoo.com',
  'jobs': ['Archaeologist',
   'Analytical chemist',
   'Surveyor, planning and development',
   'Architect'],
  'id': 189030,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'zmartin',
  'name': 'Kyle Harrison',
  'sex': 'M',
  'address': '35728 George Harbors\nPalmerhaven, NY 19496',
  'mail': 'kfoster@gmail.com',
  'jobs': ['Social researcher', 'Dietitian', 'Engineer, chemical'],
  'id': 524879,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'richard14',
  'name': 'Carla Miller',
  'sex': 'F',
  'address': '0975 Patton Points Suite 520\nGutierrezburgh, MI 89035',
  'mail': 'jermaine23@yahoo.com',
  'jobs': ['Transport planner',
   'Radiographer, diagnostic',
   'Therapist, sports',
   'Facilities manager'],
  'id': 470110,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'amy62',
  'name': 'Nicole Smith',
  'sex': 'F',
  'address': '798 Torres Circles\nComptonmouth, AL 88224',
  'mail': 'fcharles@hotmail.com',
  'jobs': ['Scientist, audiological',
   'Learning mentor',
   'Air broker',
   'Oceanographer'],
  'id': 131674,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'sstrickland',
  'name': 'Sandra Clark',
  'sex': 'F',
  'address': '909 William Springs Apt. 438\nRhondaport, WY 17145',
  'mail': 'chavezrobert@yahoo.com',
  'jobs': ['Psychotherapist, dance movement',
   'Physicist, medical',
   'Equities trader',
   'Radiation protection practitioner'],
  'id': 303454,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'icervantes',
  'name': 'Deborah Conrad',
  'sex': 'F',
  'address': '75565 Parrish Skyway Apt. 904\nMurphyhaven, OR 23100',
  'mail': 'maldonadocourtney@yahoo.com',
  'jobs': ['Dance movement psychotherapist',
   'Theatre manager',
   'Electrical engineer',
   'Site engineer'],
  'id': 1618462,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'ydavis',
  'name': 'Judith Richardson',
  'sex': 'F',
  'address': '027 Pamela Parkway Suite 059\nWhiteton, WV 30405',
  'mail': 'turnerkathryn@hotmail.com',
  'jobs': ['Phytotherapist',
   'Occupational psychologist',
   'Librarian, academic',
   'Physicist, medical',
   'Merchandiser, retail'],
  'id': 789314,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'luceroashley',
  'name': 'Molly Mooney',
  'sex': 'F',
  'address': '6371 Robert Corners\nEast Michaelland, ND 55885',
  'mail': 'lharrington@gmail.com',
  'jobs': ['Planning and development surveyor',
   'Environmental education officer',
   'Arts development officer',
   'Surveyor, land/geomatics'],
  'id': 205783,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'mariaporter',
  'name': 'Michael Johnson',
  'sex': 'M',
  'address': '65191 Sarah Islands Apt. 215\nLisaborough, VA 81648',
  'mail': 'davidshah@yahoo.com',
  'jobs': ['Horticultural therapist',
   'Recruitment consultant',
   'Financial planner',
   'Energy manager',
   'Editor, magazine features'],
  'id': 63098,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'kristen66',
  'name': 'Christy Jones DDS',
  'sex': 'F',
  'address': '9705 Christopher Crossing\nNew Matthewland, ND 15813',
  'mail': 'carlareed@yahoo.com',
  'jobs': ['Nature conservation officer',
   'Scientist, forensic',
   'Geologist, engineering'],
  'id': 193516,
  'top_job': 'Scientist, research (physical sciences)'},
 {'username': 'nunezjeffrey',
  'name': 'Albert Richards',
  'sex': 'M',

In [21]:
top_5_jobs = {}
for contributor in contributors:
    for job in contributor['jobs']:
        if job in top_5_jobs:
            top_5_jobs[job] += 1
        else:
            top_5_jobs[job] = 1

top_5_jobs = sorted(top_5_jobs.items(), key=lambda x: x[1], reverse=True)[:5]
top_5_jobs

[('Chemical engineer', 42),
 ('Chief Operating Officer', 41),
 ('Dance movement psychotherapist', 41),
 ('Bookseller', 41),
 ('Telecommunications researcher', 41)]

1.3 Создайте `pd.DataFrame` `contributors_df`, имеющий столбцы `id`, `username` и `sex` и `n_jobs`. Столбец `n_jobs` содержит кол-во должностей пользователя. При необходимости вы можете преобразовать исходные данные в списке `contributors` в удобный для создания `pd.DataFrame` вид.

Сгруппируйте полученные данные по столбцам `n_jobs` и `sex`. Выведите на экран серию `pd.Series`, в которой содержится информация о количестве человек в каждой группе.

In [9]:
import pandas as pd

In [10]:
contributors_df = pd.DataFrame(contributors)
n_jobs = contributors_df['jobs'].apply(len)
contributors_df['n_jobs'] = n_jobs

In [11]:
# оставить только столбцы id, username, sex, n_job в contributors_df
contributors_df.drop(['mail', 'jobs', 'top_job', 'name', 'address'], axis=1, inplace=True)
contributors_df

           username sex       id  n_jobs
0           uhebert   F    35193       5
1       vickitaylor   F    91970       3
2       sheilaadams   F  1848091       5
3          nicole82   F    50969       3
4            jean67   M   676820       4
...             ...  ..      ...     ...
4195  stevenspencer   F   423555       4
4196      rwilliams   M    35251       5
4197      lmartinez   F   135887       5
4198     brendahill   M   212714       4
4199       mistyray   F   344321       3

[4200 rows x 4 columns]

In [12]:
df = contributors_df.groupby('sex')['n_jobs'].value_counts()
df

sex  n_jobs
F    4         733
     3         703
     5         700
M    4         704
     3         690
     5         670
Name: n_jobs, dtype: int64

### XML

In [14]:
from bs4 import BeautifulSoup as bs

2.1 По данным файла `steps_sample.xml` сформируйте словарь с шагами по каждому рецепту вида `{id_рецепта: ["шаг1", "шаг2"]}`. Сохраните этот словарь в файл `steps_sample.json`. Выведите на экран шаги рецепта с id `84797`.

In [15]:
# make a dict with steps for each recipe {recipe_id: ["step1", "step2"]} from steps_sample.xml

In [16]:
with open('03_data_files_data/steps_sample.xml') as f:
    steps = bs(f, 'xml')

In [17]:
recipes_steps = {}

current_id = steps.find('id')
while current_id:
  recipes_steps[current_id.text] = [i.text for i in current_id.find_next('steps').find_all('step')]
  current_id = current_id.find_next('id')

In [18]:
recipes_steps

{'44123': ['in 1 / 4 cup butter , saute carrots , onion , celery and broccoli stems for 5 minutes',
  'add thyme , oregano and basil',
  'saute 5 minutes more',
  'add wine and deglaze pan',
  'add hot chicken stock and reduce by one-third',
  'add worcestershire sauce , tabasco , smoked chicken , beans and broccoli florets',
  'simmer 5 minutes',
  'add cream , simmer 5 minutes more and season to taste',
  'drop in remaining butter , piece by piece , stirring until melted and serve immediately',
  'smoked chicken: on a covered grill , slightly smoke boneless chicken , cooking to medium rare',
  'chef meskan uses applewood chips and does not allow the grill to become too hot'],
 '67664': ['mix all the ingredients using a blender',
  'pour into popsicle molds',
  'freeze and enjoy !'],
 '38798': ['combine all ingredients in a large bowl and mix well',
  'shape into one-inch balls',
  'cover and refrigerate or freeze until ready to bake',
  'preheat oven to 350 degrees',
  'place on ungreased baking sheet and bake until light brown'],
 '35173': ['lay out sandwich rolls on jelly roll pans / cookie sheets',
  'melt butter , mix in italian dressing mix',
  'using a pastry or bbq brush , graciously apply seasoned butter to the top of the"bottom bun" and the top of the top bun',
  "don't miss this step , i don't know why , but it does make a difference !",
  'here is where i create an assembly line w / the bottoms of the buns',
  'layer each bun w / ham , then swiss cheese , turkey , then cheddar cheese , pepperoni , then mozzerella cheese',
  'place"lids" on buns and place in 425 degree oven for approximly 12-15 minutes , or until you see the tops start to turn golden brown'],
 '84797': ['honey mustard sauce: whisk all the ingredients together serve warm or cold',
  'easy bbq sauce: combine all ingredients in a pot& cook over low heat until the sugar is dissolved',
  'serve warm or cold',
  'garlic dill sauce: mix all the ingredients and chill until ready to serve'],
 '44045': ['combine eggs , flour , baking powder , salt& pepper with the corn',
  'mix thoroughly',
  'add cream to mixture',
  'melt fat in frying pan& drop corn mixture by spoonfuls into the hot fat',
  'brown on both sides',
  'serve w / syrup'],
 '107229': ['cook pasta in salted water until al dente',
  'drain',
  'steam broccoli , set aside',
  'whisk next 6 ingredients together in large serving bowl',
  'add hot pasta',
  'stir in onions , broccoli , and chicken',
  'toss in cilantro',
  'sprinkle on sesame seeds'],
 '95926': ['spread a tablespoon on one side of each slice on bread',
  'peel and cut the bananas into 1 / 4-inch round slices',
  'lay the slices on two of the slices of bread and then top with the other half',
  'enjoy !'],
 '453467': ['pre-heat oven the 350 degrees f',
  'in a mixing bowl , sift together the flours and baking powder',
  'set aside',
  'in another mixing bowl , blend together the sugars , margarine , and salt until light and fluffy',
  'add the eggs , water , and vanilla to the margarine / sugar mixture and mix together until well combined',
  'add in the flour mixture to the wet ingredients and blend until combined',
  'scrape down the sides of the bowl and add the chocolate chips',
  'mix until combined',
  'scrape down the sides to the bowl again',
  'using an ice cream scoop , scoop evenly rounded balls of dough and place of cookie sheet about 1 - 2 inches apart to allow for spreading during baking',
  'bake for 10 - 15 minutes or until golden brown on the outside and soft & chewy in the center',
  'serve hot and enjoy !'],
 '306168': ['preheat oven to 350 degrees',
  'spray a 2 quart baking dish with cooking spray , set aside',
  'in a large bowl mix together broccoli , soup , one cup of cheese , garlic powder , pepper , salt , milk , 1 cup of french onions , and soy sauce',
  'pour into baking dish , sprinkle remaining cheese over top',
  'bake for 25 minutes or until cheese is lightly browned',
  'sprinkle with rest of french fried onions and bake until onions are browned and cheese is bubbly , about 10 more minutes'],
 '50662': ['coat the meat with 1 / 2 c of flour and the paprika',
  'brown in vegetable oil',
  'transfer to a casserole dish',
  'add can of onions',
  'combine one can of the chicken soup and one can water',
  'pour over meat and onions',
  'bake at 350 for 45 minutes',
  'while the meat is baking-- combine 2 c flour , the baking powder , salt , poultry seasoning , celery seed , onion flakes and poppy seeds',
  'mix well , and add 1 / 4 c oil and 1 c milk',
  'drop tablespoons of dough into breadcrumbs which you have mixed with melted butter',
  'put dumplings on top of the meat',
  'increase heat to 425 and bake for another 20 minutes',
  'make sauce',
  'combine one can of cream of chicken soup and sour cream',
  'heat sauce and serve over meat and dumplings'],
 '118843': ['mix all ingredients together just until blended',
  'spoon large tbspfuls onto a baking sheet',
  'bake at 350 for 10-14 minutes'],
 '69190': ['cook potatoes , onions , celery , and carrots in water until tender',
  'meanwhile , in other pan , put in milk , butter , cream of chicken , cream of celery , and bullion cubes on low heat',
  'when potatoes and the vegetables are tender , pour in the milk , butter , the cream of chicken and cream of celery , with the bullion cubes into the pan with the potatoes',
  'put on medium heat and stir in potato flakes occasionally',
  'enjoy !'],
 '503475': ['beat the eggs lightly and add the milk',
  'combine the flour , sugar and salt',
  'stir the flour mixture into the egg mixture , stirring in the cup of cream as you mix',
  'fry the apple slices in butter in a skillet',
  'preheat oven to 500 degree',
  'cover the bottom of an oven-proof baking dish , or heavy skillet , with apples',
  'pour the batter over slices and bake in a preheated 500 oven',
  'when nearly done , remove from oven and sprinkle here and there with a mixture of sugar and cinnamon to taste',
  'place dabs of butter on the pancake and return to oven until browned',
  'just before serving , sprinkle with lemon juice , and cut into triangles'],
 '149593': ['set oven to 400 degrees',
  'set oven rack to second-lowest position',
  'grease 12 regular size muffin tins or line with paper muffin liners',
  'in a bowl sift together flour , 1 / 2 cup plus 2 tablespoons sugar , baking powder , baking soda and salt',
  'in another bowl whisk together melted butter with sour cream , egg and vanilla or almond extract',
  'stir in the butter mixture into the flour mixture',
  'stir with a wooden spoon just until combined',
  'divide the batter between each muffin tin',
  'if you want you can sprinkle with a topping',
  'bake for about 20 minutes or until muffins test done'],
 '200148': ['for crust:',
  'melt margarine and blend well with graham cracker cumbs and sweetener',
  'press well into bottom of spring-form pan or round cake pan',
  'bake at 350f for 10 minutes',
  'let cool',
  'filling:',
  'mash tofu with vegan cream cheese',
  'add all other ingredients to tofu mixture and whip with hand mixer until well blended and very creamy',
  'try to get all tofu lumps out',
  'pour into crust and bake at 350f for 45-50 minutes',
  'turn off oven and leave in for 15 minutes more to help set center',
  'when done edges should be golden and starting to pull away from sides of pan , center should be soft set',
  'cool about an hour then refrigerate another 3 hours to set center',
  'keep refrigerated',
  'helpful hints: draining the tofu well is important',
  "too much liquid and the center won't set well",
  'after slicing the cake place a paper towel in the cut out section before returning it to the frige',
  'this will absorb any fluid that will condense on the plate or in the pan and keep the bottom of the cake from getting too soggy'],
 '310570': ['first - let me explain the feta',
  'we have an italian market that sells fresh fruits and veggies etc',
  'and they have a fresh cheese section',
  'i always buy a block of french feta cheese',
  'i use half for this recipe and the rest for omelets etc',
  "you can use the prepacked feta but if you want the full experience you'll need a lot",
  'also , you may use other variety of feta the french is very salty which is why i add cottage cheese',
  'it kind of balances out the saltiness abit',
  'you just need 1 package of phyllo',
  'mine says 32 oz , buy the long box not the country',
  'preheat oven to 350f',
  'in large mixing bowl beat eggs , add 2 cups milk and mix well',
  'take your block of feta and cut in half',
  'use one 1 / 2 and refrigerate the other',
  'crumble the feta into the egg mix and add cottage cheese',
  'make sure you have nice chunks',
  'mix well , the mixture should be thick and very lumpy',
  'if too thick add more milk',
  'take a large deep baking dish',
  'sprinkle oil on bottom only',
  'lay one sheet phyllo and drizzle with oil , continue until you have 4 sheets',
  'when you add the last sheet place your hand flat on the phyllo sheets and gently gather , without tearing by pulling the sides slightly toward center',
  ':)',
  "use 1 full ladle of the egg / feta mixture onto the layer , you don't need to cover all the phyllo just don't leave the feta in one spot distribute",
  'layer another phyllo sheet and sprinkle with oil',
  'layer another sheet of phyllo and again crumple the center then sprinkle the oil',
  'one ladle of the egg / feta mix',
  'continue in this pattern',
  'if you see that you have alot of the egg / feta mix left you can start to add more than the 1 ladle',
  'your last layer should be 3-4 layers of phyllo',
  "don't sprinkle with oil yet",
  'take a soup spoon and with the handle , tuck in the sides',
  'now sprinkle with oil',
  'bake for about 30-40 minutes or until the top is puffed and nicely browned',
  'your kitchen with smell wonderful',
  'the burek will puff high off the top of the pan but once cooled will drop',
  'you must cool completely or you will nto be able to cut with out it falling apart',
  "it's moist and a bit salty and goes great with a nice cold beer ! you can serve as main meal with salad or as appetizer"],
 '95534': ['preheat oven to 325f',
  'sprinkle the roast with garlic powder , oregano and pepper , then cook roast , uncovered , in a shallow roasting pan , about 30 minutes per pound',
  "roast will be very rare-- don't overcook it !",
  'let cool slightly , then thinly slice',
  "add to the roast's pan drippings: the boiling water , bouillon cubes , oregano , thyme , pepper , tabasco sauce , garlic and worcestershire sauce",
  'simmer for 20 minutes , scraping up the browned bits',
  'taste for salt and add some if you wish',
  'add the sliced beef',
  'cover and marinate in da gravy overnight',
  'reheat the next day and serve in crusty italian sandwich rolls'],
 '109818': ['preheat oven to 350f',
  'cook bacon until crisp',
  'drain grease and crumble into fine bits',
  'peel and slice carrots , place into baking dish',
  'add tomato soup , bacon and sugar and stir well',
  'bake for 30-45 minutes until bubbly',
  'eat and enjoy !'],
 '66932': ['heat 1 tbsp oil in pan and saut mushrooms until browned',
  'remove from heat',
  'heat remaining oil in pan and add rice',
  'add egg and mix until rice is thoroughly coated with egg',
  'cook for 5-10 minutes on high , or until egg is lightly browned',
  'combine rice mixture and vegetables in large bowl and stir until vegetables are well mixed',
  'add soy sauce to taste and serve'],
 '226001': ['heat water and butter to rolling boil',
  'stir in flour , stirring vigorously over low heat about 1 minute , or until mixture forms a ball',
  'remove from heat',
  'beat in eggs all at one time and continue beating until smooth',
  'drop dough by scant 1 / 4 cupfuls about 3" apart on ungreased baking sheet',
  'bake at 400 for 35 to 40 minutes , or until puffed and golden',
  'cool out of draft',
  'cut in half horizontally , open , and remove any uncooked filaments of dough',
  'make dream whip according to package directions',
  'make pudding with only half the milk it calls for',
  'quickly add the pudding to the dream whip and mix well',
  "fill cream puffs , sprinkle with a little powdered sugar and refrigerate until serving -- if you don't eat them first !"],
 '125195': ['in large bowl , combine mayo , relish , sugar , seas',
  'salt and mustard',
  "gently fold in rest of ingredients adding peas last so they don't get broken up and mushy",
  'chill',
  'if you like it extra creamy , double the sauce'],
 '141939': ['in a large bowl whisk the buttermilk , oil , hot pepper sauce , minced garlic , dijon mustard , 1 teaspoon salt and about 1 / 2 teaspoon black pepper',
  'add in sliced onion and chicken pieces',
  'turn to coat / mix well',
  'cover and refrigerate for a minimum of 4 hours or up 24 hours , turning occasionally',
  'place a cookie rack on a foil-lined 15x10-inch baking sheet',
  'in a bowl mix together dry breadcrumbs , parmesan cheese , flour , thyme spice , paprika , cayenne pepper , 1-1 / 2 teaspoon seasoned salt salt and garlic powder',
  'remove the chicken pieces from marinade , allowing any excess marinade to drip off the chicken',
  'dip the chicken pieces into the breadcrumb mixture and turn to coat completely',
  'arrange chicken on rack or racks on the baking sheets',
  'let chicken stand for 30 minutes , no more no less !',
  'set oven to 425f',
  'drizzle the melted butter over the chicken pieces',
  'bake until crisp , golden and cook through about 45 minutes'],
 '250883': ['beat cream cheese , limeade concentrate and orange juice in medium bowl with electric mixer on medium speed until well blended',
  'gently stir in cool whip topping',
  'cover',
  'refrigerate at least one hour',
  'serve with cut-up fresh fruit',
  'to grill fruit:',
  'peaches , nectarines and plums get a deep caramel-like flavor when cooked on the grill',
  "here's how to do it",
  'put pieces of fresh fruit on skewers',
  "use fruit that's just staring to soften , so that it stays firmly on the skewers",
  'sprinkle fruit with cinnamon or nutmeg',
  'place fruit on the grill for a minute to sear',
  'check the underside',
  "once it's golden with grill marks , turn it over to finish cooking"],
 '120297': ['preheat the oven to 200c',
  'wash the potatoes to remove any dirt , pat dry with paper towels',
  'prick the potatoes all over with a fork , brush with olive oil and season to taste with salt and pepper',
  'place the potatoes on a lightly greased baking tray and bake for about an hour or until cooked through',
  'cool for about 10 minutes',
  'while the potatoes are roasting , drain the chickpeas , place in a large mixing bowl and mash with a fork',
  'add the ground coriander , the cumin , the crushed garlic and half the fresh coriander',
  'cover the bowl with with plastic wrap , and set aside',
  'once they have cooled , taking care to keep the shells intact , halve the cooked potatoes and scoop out the flesh',
  'mash the potato flesh until smooth and gently mix with the chickpea mixture',
  'fold in the yoghurt and tahini , and add a little more of either of these if the mixture seems too dry , season with the pepper and salt , to taste',
  'place the potato shells on a lightly greased baking tray and fill them with the potato and chickpea mixture',
  'place the filled potato shells in the oven and bake for 10-15 minutes , or until heated through',
  'serve the potatoes with the remaining half of the chopped coriander'],
 '147477': ['mix together and bake until cheese melts',
  'best when served warm with assorted crackers',
  'can be used chilled as a spread'],
 '223349': ['heat oil in a nonstick skillet over medium high heat and add eggplant and cook until almost soft',
  'bake spaghetti squash at 450f for 1-2 hours until firm to the touch , let cool and then scoop out pulp',
  'add peppers , onions and oregano to eggplant and saut until tender',
  'stir in shrimp',
  'cover and steam , stirring every so often',
  'add in spaghetti squash and cook for less than a minute',
  'add olives and parsley: toss again & serve !'],
 '60938': ['preheat oven to 375f',
  'cook the diced bacon until crispy , remove from bacon fat and drain on paper towel',
  'forget everything you were ever taught about peeling potatoes , and peel them with a knife leaving a good bit of potato on the skin',
  'retain center of potatoes for another recipe , or slice them into wedges and cook in the same manner as the potato skins',
  'deep fry the potato skins until crispy and golden',
  'drain thoroughly and salt to taste',
  'spread the potato skins evenly on a pizza pan',
  'sprinkle evenly with the green onions , cheese and bacon',
  'bake for 10-15 minutes until hot and cheddar is melted',
  'serve hot with sour cream for dipping'],
 '302399': ['preheat oven to 400 degrees',
  'lightly grease a cookie sheet',
  'remove the buiscuits from the can and separate',
  'place one buiscuit in the center and place the remaining buiscuit around it slightly overlapping',
  'now flatten them out with your fingers into a 10 inch circle',
  'brush with the olive oil',
  'sprinkle with the remaining ingredients',
  'you can use any kind of cheese you have on hand',
  'chili powder and monterey jack and some chopped chillies give you a great tex-mex bread',
  'bake about 15 minute until edges are nice and brown',
  'pull apart to serve'],
 '342620': ['preheat oven to 350 degrees',
  'while oven is preheating , mix in a large bowl all ingredients except for the 1 / 8 cup of bbq sauce',
  'spray a 2 quart baking dish with the cooking spray',
  'pour meatloaf into dish , and free form into a loaf shape',
  'bake for 45 minutes , then drain if needed',
  'take remaining bbq sauce and spread over top and sides',
  'return meatloaf to over and bake for 10 to 15 minutes',
  'let meatloaf "rest " for 10 minutes , serve and enjoy',
  ':)'],
 '296983': ['preheat oven to gas mark 8',
  'cut your potatoes into 1 inch chunks',
  'toss in a bowl the potatoes in the oil with the rosemary and lemon juice and lemon zest and garlic',
  'chuck the lot onto a baking tray not forgetting to scrape herbs and oil from the bowl',
  'bake for twenty minutes while listening to funky tunes and enjoying the yumminess that is to come',
  'check that potatoes are firm yet "give" with a fork',
  'squish them a little bit with a fork and put back in oven for another 10 minutes on gas mark 3',
  'listen to more tunes',
  'serve with a squirt of fresh lemon and with greek or curry or vegan stuff or just eat out of pan',
  'i suggest tatskiki',
  'you can pulverize this into a dip using more olive oil and lemon juice or eat it chunky',
  'i like chunks',
  'i reckon this would make an ace potato salad base',
  "i absolutely hate mayonnaise , so there's no chance of me making that ever ! however you're welcome to try--i'll let you"],
 '166089': ['for immediate cooking:',
  'preheat oven to 350f',
  'combine sauce ingredients and blend until smooth',
  'toss chicken with sauce and place into a large baking dish',
  'bake until chicken juices run clear',
  'for freezing:',
  'combine sauce ingredients until smooth',
  'place sauce and chicken into a 1-gallon freezer bag',
  'shake to coat chicken',
  'lay flat in freezer',
  'to thaw and cook:',
  'thaw completely',
  'preheat the oven to 350f',
  'empty the contents of the bag into a large baking dish and bake until the juices run clear'],
 '129581': ['preheat over to 350f',
  'put all ingredients for the cake in a bowl',
  'mix on low for 1 minute to combine',
  'scrape bowl',
  'mix on medium high for a full 3 minutes to make it light and fluffy',
  "spray an angel tube pan or bundt pan with baker's spray",
  'pour batter in pan and bake for 45 to 50 minutes until done',
  'let cool in pan and then turn out onto you serving platter',

In [19]:
with open('steps_sample.json', 'w', encoding='utf-8') as f:
    json.dump(recipes_steps, f, indent=2) # indent - отступы, json.dump - запись в файл

2.2 Получите список идентификаторов рецептов, в этапах выполнения которых есть информация о времени (часы или минуты). Для отбора подходящих рецептов обратите внимание на атрибуты соответствующих тэгов. Выведите на экран количество таких рецептов.

In [21]:
def get_recipes_with_time():
  curr = steps.find('id')
  while curr:
    steps_f = curr.find_next('steps')
    if steps_f.find('step', {'has_minutes': 1}) or steps_f.find('step', {'has_hours': 1}):
      yield curr.text 
    curr = curr.find_next('id')
s = [i for i in get_recipes_with_time()]
s

['44123',
 '35173',
 '453467',
 '306168',
 '50662',
 '118843',
 '149593',
 '200148',
 '310570',
 '95534',
 '109818',
 '66932',
 '226001',
 '141939',
 '250883',
 '120297',
 '223349',
 '60938',
 '302399',
 '342620',
 '296983',
 '129581',
 '325714',
 '487173',
 '447429',
 '137701',
 '63346',
 '342619',
 '383120',
 '463219',
 '39172',
 '216068',
 '173730',
 '287778',
 '437637',
 '123115',
 '371549',
 '376813',
 '390230',
 '401605',
 '306590',
 '299968',
 '192542',
 '147563',
 '193719',
 '38852',
 '250232',
 '437219',
 '77380',
 '21357',
 '198343',
 '129919',
 '375376',
 '63131',
 '24760',
 '375362',
 '217296',
 '435816',
 '198073',
 '202949',
 '367828',
 '140610',
 '392181',
 '468143',
 '176996',
 '290187',
 '459738',
 '111198',
 '33246',
 '302498',
 '165438',
 '267159',
 '401283',
 '428566',
 '533190',
 '478546',
 '40228',
 '255985',
 '402246',
 '180817',
 '133326',
 '513963',
 '213395',
 '482111',
 '292147',
 '235003',
 '449768',
 '257696',
 '53353',
 '115160',
 '140172',
 '392598',
 '356163',
 '140173',
 '289025',
 '291409',
 '282812',
 '489337',
 '250900',
 '160494',
 '245950',
 '388578',
 '360881',
 '101260',
 '256464',
 '122791',
 '162657',
 '166483',
 '385415',
 '120462',
 '128544',
 '257111',
 '388488',
 '353419',
 '114204',
 '430737',
 '166082',
 '36072',
 '79826',
 '63069',
 '317798',
 '468765',
 '258970',
 '128027',
 '33947',
 '122817',
 '423528',
 '210766',
 '234120',
 '311959',
 '324047',
 '313237',
 '394191',
 '448832',
 '311313',
 '157534',
 '82136',
 '281251',
 '234531',
 '100633',
 '3441',
 '141164',
 '329881',
 '64631',
 '333395',
 '99798',
 '276601',
 '104588',
 '400025',
 '15541',
 '241276',
 '148114',
 '192212',
 '62088',
 '88125',
 '15646',
 '141847',
 '33849',
 '35287',
 '21629',
 '325571',
 '116672',
 '395196',
 '345089',
 '14912',
 '50854',
 '297671',
 '228000',
 '28641',
 '486851',
 '385071',
 '87105',
 '407747',
 '151148',
 '111559',
 '151131',
 '163148',
 '473574',
 '58045',
 '13671',
 '250024',
 '140171',
 '209459',
 '313613',
 '100590',
 '496614',
 '23613',
 '330512',
 '331269',
 '387435',
 '450975',
 '411729',
 '18985',
 '387106',
 '298089',
 '315233',
 '361446',
 '331174',
 '429949',
 '254176',
 '407621',
 '412075',
 '429759',
 '139718',
 '149966',
 '128563',
 '494527',
 '437455',
 '103153',
 '423582',
 '59386',
 '22567',
 '240415',
 '115776',
 '140174',
 '446600',
 '518151',
 '213132',
 '213133',
 '174129',
 '438486',
 '335920',
 '56202',
 '155405',
 '263019',
 '324404',
 '243425',
 '23378',
 '79312',
 '14873',
 '377658',
 '329139',
 '331719',
 '463122',
 '354751',
 '223979',
 '112853',
 '392262',
 '437642',
 '222079',
 '363962',
 '532656',
 '115831',
 '227248',
 '277764',
 '67203',
 '206008',
 '392927',
 '59334',
 '330611',
 '76433',
 '102749',
 '383729',
 '13709',
 '29512',
 '230004',
 '40050',
 '277562',
 '69990',
 '21360',
 '191671',
 '234169',
 '244294',
 '113458',
 '98942',
 '57566',
 '377020',
 '373269',
 '131977',
 '230060',
 '482020',
 '241632',
 '398090',
 '428080',
 '455193',
 '172783',
 '229599',
 '172781',
 '173486',
 '25020',
 '130759',
 '170021',
 '336166',
 '184074',
 '141308',
 '177987',
 '143286',
 '504294',
 '183929',
 '170081',
 '336314',
 '320973',
 '387284',
 '151748',
 '493636',
 '301164',
 '301365',
 '447967',
 '307870',
 '171809',
 '102525',
 '336627',
 '21302',
 '281593',
 '403180',
 '503265',
 '204012',
 '425294',
 '290003',
 '60583',
 '174606',
 '76727',
 '44570',
 '403438',
 '249318',
 '181765',
 '316172',
 '313942',
 '120135',
 '462351',
 '242179',
 '232548',
 '244477',
 '171097',
 '175975',
 '409088',
 '50337',
 '105093',
 '98694',
 '179987',
 '184727',
 '144568',
 '356701',
 '159732',
 '319005',
 '370746',
 '385942',
 '387136',
 '361524',
 '125847',
 '97066',
 '48864',
 '34833',
 '101429',
 '414085',
 '231161',
 '37313',
 '238000',
 '315346',
 '435173',
 '289893',
 '489028',
 '19104',
 '186631',
 '379357',
 '36009',
 '11975',
 '11141',
 '174645',
 '55510',
 '413783',
 '426211',
 '373582',
 '436664',
 '200227',
 '339114',
 '22742',
 '88845',
 '143795',
 '15086',
 '369241',
 '370775',
 '402421',
 '476489',
 '490199',
 '143938',
 '335824',
 '359713',
 '204147',
 '14613',
 '22337',
 '386614',
 '487671',
 '179011',
 '502995',
 '47545',
 '519547',
 '335876',
 '179210',
 '370018',
 '412006',
 '136451',
 '57757',
 '136514',
 '429293',
 '213177',
 '339697',
 '80474',
 '401584',
 '482653',
 '41990',
 '26809',
 '118667',
 '183118',
 '115721',
 '148060',
 '407545',
 '201417',
 '370125',
 '15458',
 '403878',
 '402687',
 '160310',
 '29448',
 '438204',
 '106417',
 '124673',
 '291364',
 '217021',
 '99570',
 '12441',
 '137010',
 '161604',
 '228901',
 '308383',
 '190394',
 '303928',
 '66815',
 '108524',
 '149731',
 '39031',
 '118016',
 '130754',
 '112868',
 '507927',
 '73602',
 '485171',
 '105886',
 '510215',
 '396740',
 '394291',
 '49648',
 '70271',
 '455028',
 '91981',
 '306676',
 '465254',
 '242952',
 '344915',
 '424845',
 '225426',
 '248926',
 '354791',
 '155788',
 '452649',
 '357052',
 '222953',
 '423344',
 '180696',
 '473974',
 '26748',
 '23964',
 '198137',
 '266146',
 '249918',
 '175109',
 '378968',
 '316418',
 '255570',
 '392740',
 '314181',
 '124735',
 '388844',
 '490605',
 '386803',
 '83061',
 '284273',
 '338907',
 '53878',
 '21019',
 '214316',
 '283443',
 '229406',
 '83959',
 '291555',
 '279302',
 '395016',
 '32550',
 '69233',
 '287526',
 '304996',
 '97032',
 '334915',
 '179128',
 '107674',
 '234952',
 '284208',
 '33081',
 '233539',
 '119839',
 '51982',
 '153',
 '407377',
 '29977',
 '135672',
 '518120',
 '40858',
 '44063',
 '50755',
 '147802',
 '291228',
 '116798',
 '205649',
 '224037',
 '362623',
 '144411',
 '318312',
 '346944',
 '472418',
 '111955',
 '110887',
 '466175',
 '499403',
 '256775',
 '116061',
 '302957',
 '428980',
 '37161',
 '62012',
 '125915',
 '473291',
 '153430',
 '8448',
 '268036',
 '244742',
 '97490',
 '244363',
 '272003',
 '187946',
 '193208',
 '29537',
 '338711',
 '65729',
 '233728',
 '229143',
 '170342',
 '88978',
 '442149',
 '441945',
 '226753',
 '25947',
 '484063',
 '69776',
 '28545',
 '343461',
 '81945',
 '305163',
 '412424',
 '113306',
 '434512',
 '476007',
 '83893',
 '84840',
 '125381',
 '304543',
 '103379',
 '224122',
 '495369',
 '59687',
 '57786',
 '395585',
 '243008',
 '229727',
 '39398',
 '23163',
 '64952',
 '168017',
 '164072',
 '311630',
 '384056',
 '131965',
 '455452',
 '445734',
 '33321',
 '35014',
 '259789',
 '293253',
 '71046',
 '161307',
 '78108',
 '327588',
 '403981',
 '8327',
 '217453',
 '78442',
 '410920',
 '130409',
 '406854',
 '421824',
 '133465',
 '356277',
 '446605',
 '420119',
 '436791',
 '330876',
 '141762',
 '507760',
 '97140',
 '32571',
 '254578',
 '129786',
 '194654',
 '94187',
 '387424',
 '75123',
 '317060',
 '315847',
 '102889',
 '31777',
 '508642',
 '12780',
 '243010',
 '107233',
 '411505',
 '28745',
 '123900',
 '259986',
 '317573',
 '388864',
 '74419',
 '140873',
 '190637',
 '267631',
 '490291',
 '121123',
 '400101',
 '423999',
 '403593',
 '205094',
 '494482',
 '317235',
 '422794',
 '457603',
 '309809',
 '334186',
 '48738',
 '193400',
 '105209',
 '193732',
 '374277',
 '50078',
 '154372',
 '66416',
 '198570',
 '70438',
 '382269',
 '147765',
 '459131',
 '317351',
 '437715',
 '279229',
 '308056',
 '241413',
 '175166',
 '15543',
 '19209',
 '222408',
 '292280',
 '327392',
 '362501',
 '329285',
 '334017',
 '253057',
 '377722',
 '71821',
 '238257',
 '264476',
 '512016',
 '145893',
 '55718',
 '78497',
 '111963',
 '238404',
 '179478',
 '122949',
 '60893',
 '131206',
 '132633',
 '331337',
 '189327',
 '65597',
 '3776',
 '361181',
 '389070',
 '507578',
 '243292',
 '302640',
 '102728',
 '8134',
 '99029',
 '335405',
 '476461',
 '466380',
 '230146',
 '356655',
 '214023',
 '171628',
 '378409',
 '398095',
 '256456',
 '53743',
 '193375',
 '100295',
 '60527',
 '79682',
 '489534',
 '57771',
 '127637',
 '140850',
 '388465',
 '102670',
 '78210',
 '338725',
 '175891',
 '75960',
 '142852',
 '40478',
 '54095',
 '12672',
 '50936',
 '40589',
 '224452',
 '400912',
 '378468',
 '146444',
 '456852',
 '107851',
 '89021',
 '330040',
 '452590',
 '403819',
 '420689',
 '191150',
 '74520',
 '460292',
 '130992',
 '346687',
 '169993',
 '449725',
 '50851',
 '521251',
 '205500',
 '331846',
 '31748',
 '20143',
 '524289',
 '203930',
 '243278',
 '253381',
 '61297',
 '43792',
 '216499',
 '176277',
 '125300',
 '145034',
 '393772',
 '499336',
 '489651',
 '23499',
 '24763',
 '123577',
 '63976',
 '485964',
 '27897',
 '46022',
 '189207',
 '273416',
 '22949',
 '61154',
 '189586',
 '138771',
 '192298',
 '260930',
 '131664',
 '211518',
 '414036',
 '189486',
 '133964',
 '202288',
 '41143',
 '104763',
 '95211',
 '116397',
 '385243',
 '116392',
 '233830',
 '105879',
 '62556',
 '36403',
 '144773',
 '2994',
 '315983',
 '116489',
 '116459',
 '83213',
 '349223',
 '35591',
 '12737',
 '158185',
 '176730',
 '279912',
 '22358',
 '68986',
 '77581',
 '69728',
 '174678',
 '135227',
 '135777',
 '414542',
 '289985',
 '456241',
 '110652',
 '91395',
 '42845',
 '280857',
 '364148',
 '94878',
 '108473',
 '206772',
 '425118',
 '529216',
 '279797',
 '426227',
 '88039',
 '98558',
 '307048',
 '295171',
 '345848',
 '46306',
 '355792',
 '480684',
 '465942',
 '406507',
 '431875',
 '317071',
 '164825',
 '177831',
 '179738',
 '307835',
 '14745',
 '171314',
 '140084',
 '354542',
 '123449',
 '22125',
 '424216',
 '32515',
 '158917',
 '410116',
 '202823',
 '379283',
 '348077',
 '233971',
 '321647',
 '183778',
 '121665',
 '456699',
 '111422',
 '478706',
 '478189',
 '449390',
 '156650',
 '256842',
 '95295',
 '136720',
 '127620',
 '85743',
 '383349',
 '249547',
 '479203',
 '293005',
 '109791',
 '470448',
 '89335',
 '303605',
 '449854',
 '38607',
 '241667',
 '180294',
 '283065',
 '267536',
 '43123',
 '170920',
 '63338',
 '332641',
 '8776',
 '389252',
 '136899',
 '191093',
 '116993',
 '202628',
 '373186',
 '356146',
 '212865',
 '119395',
 '174298',
 '388205',
 '175009',
 '482235',
 '52388',
 '256746',
 '85960',
 '506732',
 '54841',
 '299916',
 '438362',
 '352904',
 '368003',
 '81479',
 '208259',
 '125067',
 '246489',
 '247128',
 '413652',
 '267999',
 '502300',
 '173126',
 '74640',
 '135757',
 '428016',
 '504168',
 '206438',
 '96968',
 '383039',
 '52672',
 '224905',
 '32005',
 '280297',
 '14900',
 '193477',
 '181657',
 '24447',
 '498564',
 '359058',
 '308481',
 '159129',
 '259154',
 '117523',
 '387542',
 '115484',
 '166831',
 '187872',
 '239638',
 '471259',
 '23567',
 '261088',
 '287950',
 '76948',
 '279705',
 '263830',
 '177681',
 '457379',
 '130688',
 '226796',
 '249006',
 '281503',
 '69539',
 '221061',
 '133919',
 '40008',
 '278396',
 '89374',
 '386956',
 '338171',
 '91488',
 '334869',
 '133791',
 '332386',
 '183494',
 '188024',
 '298739',
 '216631',
 '476635',
 '53370',
 '314844',
 '160251',
 '249600',
 '471921',
 '478829',
 '300330',
 '314834',
 '17412',
 '256185',
 '57457',
 '7210',
 '90072',
 '439608',
 '492732',
 '61350',
 '78454',
 ...]

In [22]:
len(s)

23469

2.3 Загрузите данные из файла `recipes_sample.csv` (__ЛР2__) в таблицу `recipes`. Для строк, которые содержат пропуски в столбце `n_steps`, заполните этот столбец на основе файла  `steps_sample.xml`. Строки, в которых столбец `n_steps` заполнен, оставьте без изменений. При решении задачи не используйте метод `iterrows` и аналогичные ему, позволяющие итерироваться по таблице построчно.

Проверьте, содержит ли столбец `n_steps` пропуски. Если нет, то преобразуйте его к целочисленному типу и сохраните результаты в файл `recipes_sample_with_filled_nsteps.csv`

In [29]:
recipes = pd.read_csv("02_pandas_data/recipes_sample.csv", parse_dates=['submitted'])
recipes

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29995,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
29997,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
29998,zydeco soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN
29999,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

In [34]:
with open('03_data_files_data/steps_sample.xml') as f:
    steps = bs(f, 'xml')

In [38]:
recipes_len = {}

current_id = steps.find('id')
while current_id:
  steps_len = len(current_id.find_next('steps').find_all('step'))
  recipes_len[current_id.text] = steps_len 
  current_id = current_id.find_next('id')

recipes_len

{'44123': 11,
 '67664': 3,
 '38798': 5,
 '35173': 7,
 '84797': 4,
 '44045': 6,
 '107229': 8,
 '95926': 4,
 '453467': 12,
 '306168': 6,
 '50662': 15,
 '118843': 3,
 '69190': 5,
 '503475': 10,
 '149593': 10,
 '200148': 18,
 '310570': 38,
 '95534': 10,
 '109818': 7,
 '66932': 7,
 '226001': 12,
 '125195': 5,
 '141939': 13,
 '250883': 14,
 '120297': 14,
 '147477': 3,
 '223349': 7,
 '60938': 10,
 '302399': 11,
 '342620': 9,
 '296983': 14,
 '166089': 14,
 '129581': 33,
 '116741': 2,
 '325714': 6,
 '276594': 6,
 '487173': 30,
 '289671': 6,
 '44050': 2,
 '447429': 24,
 '137701': 18,
 '292568': 2,
 '299989': 14,
 '63346': 7,
 '342619': 9,
 '383120': 10,
 '367987': 3,
 '463219': 8,
 '39172': 8,
 '216068': 3,
 '173730': 28,
 '287778': 9,
 '437637': 10,
 '123115': 14,
 '371549': 8,
 '376813': 9,
 '134085': 4,
 '390230': 34,
 '401605': 7,
 '306590': 5,
 '303944': 13,
 '299968': 13,
 '192542': 4,
 '147563': 9,
 '193719': 16,
 '38852': 9,
 '250232': 10,
 '134787': 7,
 '437219': 9,
 '77380': 5,
 '21357': 7,
 '198343': 9,
 '129919': 12,
 '375376': 11,
 '152534': 8,
 '63131': 6,
 '24760': 8,
 '327979': 2,
 '375362': 3,
 '217296': 13,
 '121107': 12,
 '435816': 29,
 '198073': 22,
 '202949': 6,
 '26420': 2,
 '367828': 3,
 '140610': 11,
 '392181': 38,
 '468143': 10,
 '374703': 11,
 '100837': 4,
 '286484': 3,
 '176996': 6,
 '290187': 20,
 '11361': 4,
 '459738': 16,
 '111198': 11,
 '164636': 2,
 '33246': 1,
 '302498': 10,
 '378067': 5,
 '165438': 10,
 '267159': 8,
 '401283': 7,
 '428566': 4,
 '533190': 10,
 '478546': 26,
 '40228': 12,
 '255985': 20,
 '402246': 9,
 '180817': 15,
 '133326': 15,
 '513963': 12,
 '213395': 13,
 '27060': 3,
 '334201': 6,
 '482111': 2,
 '126072': 2,
 '292147': 6,
 '221429': 7,
 '218671': 5,
 '121712': 3,
 '235003': 4,
 '43669': 6,
 '449768': 19,
 '257696': 8,
 '53353': 3,
 '115160': 13,
 '140172': 4,
 '392598': 8,
 '356163': 9,
 '140173': 4,
 '289025': 9,
 '291409': 3,
 '282812': 6,
 '489337': 16,
 '250900': 10,
 '160494': 3,
 '245950': 8,
 '388578': 10,
 '360881': 10,
 '453243': 5,
 '101260': 5,
 '256464': 7,
 '122791': 18,
 '214264': 2,
 '416599': 5,
 '162657': 6,
 '166483': 9,
 '385415': 8,
 '120462': 13,
 '128544': 19,
 '257111': 11,
 '274469': 5,
 '432661': 11,
 '388488': 12,
 '353419': 9,
 '296654': 4,
 '114204': 11,
 '430737': 14,
 '166082': 16,
 '36072': 10,
 '123408': 7,
 '79826': 5,
 '63069': 11,
 '112648': 10,
 '317798': 13,
 '468765': 9,
 '505748': 3,
 '258970': 8,
 '128027': 10,
 '165096': 11,
 '33947': 11,
 '122817': 9,
 '423528': 19,
 '210766': 10,
 '234120': 5,
 '311959': 7,
 '324047': 6,
 '313237': 10,
 '394191': 5,
 '448832': 5,
 '137187': 3,
 '311313': 6,
 '157534': 12,
 '82136': 15,
 '281251': 8,
 '234531': 10,
 '100633': 10,
 '3441': 8,
 '141164': 7,
 '329881': 9,
 '64631': 17,
 '333395': 9,
 '99798': 7,
 '276601': 7,
 '67686': 4,
 '104588': 25,
 '400025': 20,
 '15541': 5,
 '57206': 12,
 '241276': 4,
 '148114': 9,
 '192212': 17,
 '62088': 14,
 '88125': 7,
 '57009': 2,
 '15646': 14,
 '141847': 6,
 '382633': 15,
 '33849': 16,
 '35287': 19,
 '21629': 5,
 '325571': 45,
 '116672': 2,
 '395196': 6,
 '345089': 10,
 '14912': 9,
 '50854': 5,
 '297671': 4,
 '228000': 10,
 '28641': 7,
 '486851': 5,
 '385071': 8,
 '87105': 8,
 '407747': 7,
 '265502': 2,
 '151148': 6,
 '111559': 3,
 '151131': 6,
 '163148': 4,
 '473574': 8,
 '58045': 7,
 '13671': 8,
 '250024': 11,
 '140171': 8,
 '209459': 4,
 '313613': 7,
 '100590': 6,
 '136471': 10,
 '496614': 16,
 '23613': 3,
 '263109': 7,
 '330512': 11,
 '331269': 6,
 '387435': 22,
 '450975': 29,
 '174369': 6,
 '365478': 12,
 '411729': 20,
 '106797': 6,
 '18985': 15,
 '387106': 8,
 '298089': 5,
 '317681': 3,
 '315233': 11,
 '25259': 11,
 '223242': 3,
 '361446': 4,
 '331174': 11,
 '55425': 8,
 '429949': 26,
 '254176': 10,
 '407621': 11,
 '504956': 3,
 '90092': 9,
 '412075': 8,
 '504948': 4,
 '125721': 1,
 '429759': 8,
 '139718': 2,
 '149966': 5,
 '128563': 14,
 '494527': 15,
 '437455': 7,
 '63907': 3,
 '315982': 2,
 '103153': 8,
 '423582': 21,
 '59386': 21,
 '22567': 5,
 '246579': 3,
 '123716': 10,
 '240415': 6,
 '115776': 7,
 '140174': 9,
 '446600': 5,
 '518151': 15,
 '213132': 18,
 '213133': 16,
 '174129': 4,
 '438486': 12,
 '335920': 15,
 '56202': 15,
 '155405': 14,
 '19618': 6,
 '263019': 11,
 '324404': 9,
 '243425': 5,
 '23378': 8,
 '281409': 10,
 '79312': 7,
 '14873': 5,
 '366021': 3,
 '377658': 5,
 '329139': 12,
 '331719': 14,
 '463122': 6,
 '354751': 3,
 '8827': 1,
 '460069': 3,
 '223979': 9,
 '112853': 11,
 '392262': 5,
 '309247': 10,
 '437642': 9,
 '222079': 10,
 '363962': 8,
 '532656': 12,
 '234856': 10,
 '115831': 9,
 '227248': 10,
 '277764': 26,
 '67203': 6,
 '206008': 6,
 '392927': 8,
 '59334': 10,
 '330611': 8,
 '76433': 9,
 '102749': 8,
 '452525': 20,
 '383729': 11,
 '13709': 11,
 '229252': 4,
 '29512': 17,
 '230004': 7,
 '40050': 7,
 '277562': 7,
 '69990': 6,
 '267714': 9,
 '21360': 5,
 '191671': 8,
 '234169': 10,
 '244294': 7,
 '113458': 9,
 '435110': 2,
 '206136': 2,
 '300355': 5,
 '281241': 1,
 '351371': 1,
 '98942': 8,
 '57566': 13,
 '377020': 12,
 '373269': 3,
 '131977': 15,
 '230060': 21,
 '189127': 3,
 '482020': 22,
 '241632': 26,
 '172729': 2,
 '398090': 5,
 '169561': 15,
 '428080': 13,
 '455193': 6,
 '172783': 7,
 '229599': 2,
 '172781': 6,
 '292695': 2,
 '173486': 14,
 '455529': 1,
 '25020': 5,
 '141617': 7,
 '130759': 9,
 '170021': 10,
 '336166': 11,
 '184074': 8,
 '141308': 10,
 '177987': 6,
 '143286': 11,
 '504294': 14,
 '183929': 9,
 '170081': 24,
 '336314': 18,
 '240135': 3,
 '485158': 1,
 '320973': 5,
 '387284': 11,
 '151748': 10,
 '493636': 5,
 '301164': 5,
 '301365': 5,
 '447967': 4,
 '307870': 9,
 '171809': 4,
 '354615': 4,
 '102525': 7,
 '336627': 28,
 '21302': 5,
 '281593': 6,
 '403180': 12,
 '503265': 8,
 '204012': 29,
 '425294': 5,
 '290003': 11,
 '60583': 15,
 '174606': 7,
 '76727': 10,
 '44570': 13,
 '403438': 8,
 '249318': 4,
 '181765': 5,
 '316172': 8,
 '313942': 6,
 '120135': 18,
 '462351': 5,
 '242179': 17,
 '232548': 4,
 '244477': 12,
 '455543': 12,
 '171097': 15,
 '175975': 16,
 '409088': 18,
 '50337': 7,
 '276396': 1,
 '105093': 15,
 '98694': 8,
 '179987': 13,
 '303710': 4,
 '184727': 21,
 '509612': 19,
 '144568': 12,
 '356701': 6,
 '159732': 6,
 '319005': 14,
 '4205': 3,
 '229376': 9,
 '60058': 7,
 '97699': 7,
 '243909': 3,
 '3258': 8,
 '370746': 11,
 '385942': 19,
 '387136': 17,
 '501197': 7,
 '361524': 6,
 '125847': 13,
 '97066': 12,
 '48864': 16,
 '123758': 5,
 '34833': 11,
 '316190': 2,
 '101429': 8,
 '414085': 7,
 '231161': 14,
 '37313': 8,
 '238000': 5,
 '315346': 23,
 '202414': 3,
 '435173': 17,
 '289893': 9,
 '489028': 13,
 '117542': 3,
 '67666': 1,
 '412091': 7,
 '19104': 10,
 '186631': 5,
 '295701': 2,
 '379357': 5,
 '36009': 7,
 '11975': 11,
 '11141': 9,
 '174645': 7,
 '55510': 7,
 '190648': 8,
 '14192': 2,
 '413783': 4,
 '380243': 4,
 '474098': 13,
 '39189': 3,
 '426211': 11,
 '497751': 6,
 '287008': 21,
 '373582': 11,
 '383147': 5,
 '436664': 22,
 '160696': 5,
 '200227': 18,
 '339114': 17,
 '22742': 17,
 '88845': 11,
 '143795': 10,
 '33565': 4,
 '388304': 8,
 '15086': 5,
 '44541': 8,
 '369241': 4,
 '370775': 16,
 '402421': 16,
 '330954': 4,
 '476489': 7,
 '314777': 3,
 '490199': 24,
 '143938': 12,
 '335824': 10,
 '316673': 3,
 '359713': 20,
 '198585': 4,
 '204147': 10,
 '211370': 2,
 '14613': 7,
 '265955': 7,
 '22337': 9,
 '386614': 10,
 '487671': 23,
 '179011': 13,
 '502995': 17,
 '47545': 12,
 '519547': 6,
 '335876': 5,
 '179210': 22,
 '370018': 15,
 '412006': 7,
 '136451': 10,
 '57757': 8,
 '160133': 2,
 '284868': 1,
 '456968': 11,
 '136514': 7,
 '429293': 16,
 '213177': 6,
 '339697': 14,
 '247025': 4,
 '15869': 5,
 '14149': 11,
 '80474': 8,
 '401584': 12,
 '482653': 12,
 '41990': 9,
 '26809': 25,
 '118667': 10,
 '183118': 9,
 '115721': 12,
 '148060': 16,
 '407545': 15,
 '201417': 17,
 '370125': 14,
 '15458': 8,
 '403878': 15,
 '402687': 20,
 '160310': 19,
 '270626': 6,
 '29448': 7,
 '438204': 18,
 '106417': 18,
 '124673': 12,
 '477848': 3,
 '291364': 19,
 '217021': 13,
 '99570': 4,
 '12441': 5,
 '137010': 10,
 '161604': 31,
 '228901': 10,
 '308383': 4,
 '393601': 8,
 '190394': 5,
 '37595': 15,
 '303928': 19,
 '66815': 13,
 '108524': 21,
 '149731': 6,
 '130679': 2,
 '39031': 6,
 '333740': 10,
 '118016': 16,
 '130754': 8,
 '112868': 20,
 '507927': 11,
 '73602': 11,
 '485171': 17,
 '121493': 10,
 '105886': 16,
 '510215': 9,
 '396740': 7,
 '394291': 19,
 '49648': 5,
 '70271': 6,
 '455028': 7,
 '229602': 1,
 '91981': 11,
 '306676': 7,
 '405479': 8,
 '465254': 8,
 '242952': 23,
 '344915': 32,
 '424845': 40,
 '101371': 2,
 '302106': 7,
 '225426': 18,
 '248926': 5,
 '354791': 7,
 '155788': 15,
 '452649': 14,
 '357052': 12,
 '222953': 7,
 '423344': 6,
 '180696': 5,
 '162268': 14,
 '256689': 3,
 '473974': 8,
 '197284': 3,
 '26748': 6,
 '342437': 9,
 '323352': 10,
 '23964': 4,
 '146801': 2,
 '198137': 7,
 '266146': 8,
 '249918': 10,
 '102336': 7,
 '90641': 4,
 '184166': 7,
 '294327': 2,
 '456752': 2,
 '175109': 11,
 '378968': 7,
 '316418': 8,
 '255570': 18,
 '260335': 7,
 '392740': 29,
 '314181': 9,
 '124735': 9,
 '291058': 9,
 '243286': 2,
 '388844': 8,
 '357968': 5,
 '490605': 13,
 '441761': 4,
 '386803': 17,
 '83061': 14,
 '284273': 4,
 '338907': 45,
 '53878': 9,
 '21019': 6,
 '214316': 13,
 '283443': 20,
 '390933': 11,
 '229406': 4,
 '83959': 10,
 '291555': 4,
 '279302': 3,
 '106260': 6,
 '395016': 15,
 '32550': 5,
 '69233': 12,
 '287526': 10,
 '304996': 6,
 '7550': 18,
 '323477': 1,
 '97032': 16,
 '334915': 13,
 '179128': 5,
 '107674': 8,
 '234952': 4,
 '284208': 7,
 '33081': 10,
 '233539': 44,
 '119839': 8,
 '51982': 4,
 '153': 19,
 '146096': 25,
 '198234': 10,
 '407377': 5,
 '29977': 8,
 '245792': 3,
 '135672': 21,
 '37152': 5,
 '518120': 43,
 '40858': 5,
 '44063': 10,
 '50755': 8,
 '427188': 2,
 '147802': 16,
 '291228': 9,
 '247103': 5,
 '116798': 2,
 '205649': 4,
 '224037': 12,
 '362623': 12,
 '144411': 16,
 '184458': 12,
 '318312': 4,
 '196426': 6,
 '464367': 3,
 '123753': 5,
 '346944': 20,
 '208190': 2,
 '142233': 6,
 '472418': 14,
 '188540': 3,
 '111955': 9,
 '110887': 14,
 '100649': 4,
 '466175': 10,
 '499403': 8,
 '256775': 6,
 '116061': 10,
 '187678': 5,
 '302957': 4,
 '112725': 1,
 '428980': 6,
 '37161': 10,
 '62012': 8,
 '125915': 3,
 '473291': 9,
 '100156': 8,
 '166813': 12,
 '153430': 8,
 '8448': 19,
 '268036': 23,
 '244742': 7,
 '97490': 7,
 '244363': 21,
 '272003': 17,
 '187946': 13,
 '145419': 21,
 '275046': 1,
 '193208': 11,
 '29537': 12,
 '26325': 7,
 '85354': 3,
 '338711': 6,
 '65729': 5,
 '233728': 13,
 '229143': 10,
 '201036': 8,
 '170342': 14,
 '88978': 3,
 '442149': 18,
 '441938': 18,
 '441945': 15,
 '107153': 4,
 '226753': 6,
 '123689': 2,
 '25947': 5,
 '484063': 10,
 '69776': 7,
 '28545': 6,
 '343461': 5,
 '81945': 15,
 '305163': 8,
 '322281': 9,
 '412424': 17,
 '61879': 8,
 '113306': 9,
 '293713': 5,
 '434512': 5,
 '264064': 3,
 '476007': 15,
 '83893': 11,
 '84849': 16,
 '84840': 9,
 '125381': 13,
 '304543': 12,
 '103379': 7,
 '224122': 10,
 '495369': 6,
 '59687': 7,
 '412171': 6,
 '121156': 2,
 '57786': 8,
 '395585': 4,
 '243008': 11,
 '229727': 10,
 '39398': 5,
 '131531': 2,
 '246286': 5,
 '23163': 4,
 '64952': 8,
 '168017': 5,
 '69168': 10,
 '164072': 7,
 '160902': 3,
 '37428': 6,
 '311630': 16,
 '5197': 3,
 '384056': 12,
 '131965': 13,
 '455452': 7,
 '445734': 7,
 '33321': 7,
 '35014': 6,
 '259789': 11,
 '293253': 12,
 '71046': 7,
 '161307': 9,
 '78108': 10,
 '327588': 21,
 '303926': 11,
 '323576': 2,
 '105454': 2,
 '403981': 24,
 '8327': 19,
 '217453': 17,
 '78442': 18,
 '410920': 11,
 '130409': 5,
 '41166': 7,
 '213724': 5,
 '406854': 17,
 '421824': 10,
 '133465': 10,
 '230428': 9,
 '227191': 3,
 '356277': 6,
 '446605': 11,
 '420119': 13,
 '436791': 10,
 '330876': 19,
 '141762': 19,
 '507760': 10,
 '97140': 7,
 '32571': 11,
 '254578': 6,
 '129786': 14,
 '194654': 18,
 '45643': 4,
 '94187': 5,
 '387424': 36,
 '75123': 6,
 '317060': 8,
 '147791': 3,
 '315847': 4,
 '102889': 6,
 '102214': 7,
 '31777': 16,
 '508642': 19,
 '12780': 6,
 '243010': 10,
 '107233': 7,
 '411505': 3,
 '28745': 9,
 '123900': 6,
 '259986': 12,
 '317573': 12,
 '388864': 12,
 '154964': 5,
 '74419': 11,
 '140873': 6,
 '190637': 12,
 '267631': 9,
 '490291': 2,
 '121123': 6,
 '400101': 62,
 '423999': 6,
 '403593': 7,
 '79749': 3,
 '339225': 2,
 '205094': 9,
 '494482': 4,
 '317235': 8,
 '422794': 7,
 '143226': 9,
 '457603': 15,
 '309809': 17,
 '264075': 2,
 '334186': 3,
 '48738': 6,
 '193400': 14,
 '105209': 12,
 '193732': 6,
 '374277': 3,
 '50078': 12,
 '154372': 13,
 '66416': 8,
 '198570': 12,
 '70438': 27,
 '382269': 5,
 '147765': 7,
 '459131': 8,
 '198350': 4,
 '317351': 13,
 '437715': 10,
 '279229': 4,
 '308056': 11,
 '130727': 2,
 '241413': 15,
 '175166': 18,
 '15543': 7,
 '19209': 13,
 '222408': 18,
 '292280': 8,
 '327392': 15,
 '362501': 7,
 '329285': 7,
 '334017': 6,
 '253057': 20,
 '377722': 7,
 '71821': 12,
 '238257': 16,
 '264476': 7,
 '512016': 1,
 '145893': 4,
 '55718': 5,
 '14479': 13,
 '484942': 5,
 '78497': 11,
 '111963': 11,
 '238404': 9,
 '179478': 12,
 '122949': 14,
 '60893': 7,
 '131206': 14,
 '132633': 9,
 '331337': 16,
 '189327': 8,
 '65597': 4,
 '3776': 9,
 '361181': 11,
 '389070': 13,
 '507578': 9,
 '243292': 12,
 '302640': 11,
 '102728': 6,
 '8134': 14,
 '99029': 8,
 '355173': 3,
 '335405': 12,
 '46041': 8,
 '476461': 7,
 '466380': 10,
 '230530': 3,
 '230146': 20,
 '356655': 11,
 '214023': 7,
 '171628': 5,
 '378409': 17,
 '398095': 4,
 '256456': 8,
 '53743': 11,
 '193375': 20,
 '291363': 10,
 '49349': 7,
 '100295': 18,
 '60527': 17,
 '79682': 9,
 '461508': 4,
 '489534': 12,
 '404419': 1,
 '275663': 3,
 '39402': 2,
 '57771': 11,
 '127637': 12,
 '140850': 6,
 '190858': 10,
 '388465': 9,
 '102670': 20,
 '78210': 14,
 '338725': 16,
 '175891': 16,
 '75960': 6,
 '399189': 4,
 '142852': 6,
 '71833': 2,
 '40478': 5,
 '54095': 13,
 '12672': 6,
 '50936': 14,
 '93365': 8,
 '272034': 3,
 '40589': 12,
 '224452': 6,
 '400912': 12,
 '378468': 5,
 '146444': 13,
 '456852': 10,
 '107851': 18,
 '89021': 3,
 '330040': 6,
 '452590': 15,
 '403819': 18,
 '420689': 11,
 '191150': 12,
 '74520': 11,
 '460292': 17,
 '130992': 6,
 '346687': 14,
 '169993': 15,
 '260352': 7,
 '158382': 7,
 '449725': 5,
 '50851': 11,
 '521251': 5,
 '205500': 15,
 '331846': 17,
 '69045': 7,
 '31748': 12,
 '20143': 15,
 '524289': 18,
 '203930': 5,
 ...}

In [39]:
recipes['n_steps'] = recipes['n_steps'].fillna(recipes['id'].map(recipes_len))

In [40]:
recipes # хуй знает почему не заполнилось

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29995,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
29997,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
29998,zydeco soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN
29999,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

### hdf

3.1 Выведите названия всех датасетов, находящихся в файле `nutrition_sample.h5`, а также размерность матриц, содержащихся в данных датасетах и их метаданные.

Формат вывода:
```
Dataset name=dataset_0 n_rows=30000 n_cols=2 col_0=recipe_id col_1=calories (#)
Dataset name=dataset_1 n_rows=30000 n_cols=2 col_0=recipe_id col_1=total fat (PDV)
Dataset name=dataset_2 n_rows=30000 n_cols=2 col_0=recipe_id col_1=sugar (PDV)
...
```

In [49]:
import h5py

In [59]:
datasets = {}
with h5py.File('03_data_files_data/nutrition_sample.h5', 'r') as h5file:
    for dataset in h5file:
        datasets[dataset] = h5file[dataset].shape
        meta = h5file[dataset].attrs

In [60]:
datasets

{'dataset_0': (30000, 2),
 'dataset_1': (30000, 2),
 'dataset_2': (30000, 2),
 'dataset_3': (30000, 2),
 'dataset_4': (30000, 2),
 'dataset_5': (30000, 2),
 'dataset_6': (30000, 2)}

In [62]:
for dataset in datasets:
    print(f'Dataset name={dataset} n_rows={datasets[dataset][0]} n_cols={datasets[dataset][1]}')

Dataset name=dataset_0 n_rows=30000 n_cols=2
Dataset name=dataset_1 n_rows=30000 n_cols=2
Dataset name=dataset_2 n_rows=30000 n_cols=2
Dataset name=dataset_3 n_rows=30000 n_cols=2
Dataset name=dataset_4 n_rows=30000 n_cols=2
Dataset name=dataset_5 n_rows=30000 n_cols=2
Dataset name=dataset_6 n_rows=30000 n_cols=2

3.2 Разбейте каждый из имеющихся датасетов на две части: 1 часть содержит только те строки, где PDV (Percent Daily Value) превышает 100%; 2 часть содержит те строки, где PDV составляет не более 100%. Создайте 2 группы в файле и разместите в них соответствующие части датасета c сохранением метаданных исходных датасетов. Итого должно получиться 2 группы, содержащие несколько датасетов. Датасеты, которые не содержат информацию о PDV, оставьте вне групп. Сохраните результаты в файл `nutrition_grouped.h5`.

3.3 Выведите названия всех групп и датасетов, находящихся в этих группах, из файла `nutrition_grouped.h5` а также размерность матриц, содержащихся в датасетах и их метаданные.

Формат вывода:
```
Dataset name=dataset_0 n_rows=30000 n_cols=2 col_0=recipe_id col_1=calories (#)
Group less_equal_than_100:
    Dataset name=less_equal_than_100/dataset_1 n_rows=28264 n_cols=2 col_0=recipe_id col_1=total fat (PDV)
    ....
Group more_than_100
    Dataset name=more_than_100/dataset_1 n_rows=1736 n_cols=2 col_0=recipe_id col_1=total fat (PDV)
    ....
....
```