# Dask Array (1)

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы:
* Макрушин С.В. Лекция "Dask"
* https://docs.dask.org/en/latest/array.html
* https://docs.dask.org/en/stable/array-chunks.html
* https://en.wikipedia.org/wiki/Taxicab_geometry
* https://docs.h5py.org/en/stable/

## Задачи для совместного разбора

1. Создайте массив размерностью 1000 на 300000, заполненный числами из стандартного нормального распределения. Исследуйте основные характеристики полученного массива.

2. Посчитайте сумму квадратов элементов массива, созданного в задаче 1. Создайте массив `np.array` такого же размера и сравните скорость решения задачи с использование `da.array` и `np.array`

## Лабораторная работа 7

__При решении данных задач не подразумевается использования циклов или генераторов Python в ходе работы с пакетами `numpy`, `pandas` и `dask`, если в задании не сказано обратного. Решения задач, в которых для обработки массивов `numpy`, структур `pandas` или структур `dask` используются явные циклы (без согласования с преподавателем), могут быть признаны некорректными и не засчитаны.__

В ходе выполнения все операции вычислений (расчет средних значений, расчет косинусной близости и т.д.) проводятся над `dask.array` и средствами пакета `dask`, если в задании не сказано обратного. Переход от `dask.array` к `numpy.array` или `pd.DataFrame` возможен исключительно для демонстрации результата в конце решения задачи. Если в задаче используются результаты выполнения предыдущих задач, то подразумевается, что вы используете результаты в виде `dask.array` (то есть то, что было получено до вызова `compute`, а не после).

<p class="task" id="1"></p>

1\. Считайте датасет `embeddings` из файла `recipe_embeddings.h5` в виде `dask.array`. Выведите на экран основную информацию о массиве: размер, количество векторов $M$ (количество строк в массиве), размерность каждого вектора $N$ (количество столбцов в массиве), тип, количество и размер сегментов.

In [ ]:
import h5py
import dask.array as da

In [ ]:
fp = h5py.File("./data/recipe_embeddings.h5")
arr = da.from_array(fp['embeddings'])
arr

<ipython-input-8-950ea435d2fe>:1: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  fp = h5py.File("./data/recipe_embeddings.h5")

dask.array<array, shape=(1200000, 312), dtype=float32, chunksize=(100000, 312), chunktype=numpy.ndarray>

<p class="task" id="2"></p>

2\. Посчитайте и выведите на экран среднее значение всех элементов массива. Исследуйте, как влияет значение аргумента `chunks` при создании `dask.array` на скорость выполнения операции поиска среднего.

Пусть $M$ - количество строк в массиве, $N$ - количество столбцов в массиве, `chunks=(r,c)`. Сравните несколько вариантов:
* $r=M$, $с \ll N$ ,
* $r \ll M$, $c=N$
* $r = M$, $c = N$
* значения $r, c$ по умолчанию.

Выберите наиболее оптимальные значения $r$ и  $c$ в смысле скорости вычислений и далее продолжайте работу с ними.

In [ ]:
%%time
arr = da.from_array(fp['embeddings'], chunks=(1200000, 30))
s = arr.mean()
s.compute()

Wall time: 4.17 s

0.002377757

In [ ]:
%%time
arr = da.from_array(fp['embeddings'], chunks=(1000, 312))
s = arr.mean()
s.compute()

Wall time: 1.46 s

0.0023777566

In [ ]:
%%time
arr = da.from_array(fp['embeddings'], chunks=(1200000, 312))
s = arr.mean()
s.compute()

Wall time: 852 ms

0.0023777678

In [ ]:
%%time
arr = da.from_array(fp['embeddings'])
s = arr.mean()
s.compute()

Wall time: 705 ms

0.0023777566

<p class="task" id="3"></p>

3\. Опишите пространство, в котором расположены эмбеддинги, посчитав минимальное и максимальное значение для каждой из координат. Сведите результаты в таблицу `pd.DataFrame`, состоящую из двух строк и 312 столбцов. Задайте индексы строк "min" и "max". Названия столбцов сделайте вида $e_i$. Выведите полученную таблицу на экран.

Решите задачу двумя способами. В первом варианте сделайте два вызова метода `compute` для расчета каждого из векторов максимальных и минимальных значений. Во втором варианте сделайте один вызов функции `dask.compute` для одновременного расчета двух векторов. Сравните время выполнения двух решений.

In [ ]:
import numpy as np
import pandas as pd
import dask

In [ ]:
%%time
min_ = arr.min(axis=0)
max_ = arr.max(axis=0)
pd.DataFrame([min_.compute(), max_.compute()], columns=['e' + str(i) for i in range(312)], index=['min', 'max'])

Wall time: 1.58 s

,e0,e1,e2,e3,e4,e5,e6,e7,e8,e9,...,e302,e303,e304,e305,e306,e307,e308,e309,e310,e311
min,-0.132803,-0.149056,-0.094468,-0.191697,-0.114229,-0.114341,-0.096039,-0.115178,-0.157275,-0.116715,...,-0.103254,-0.122285,-0.149789,-0.127703,-0.094802,-0.119690,-0.141425,-0.123732,-0.081543,-0.227348
max,0.135038,0.076125,0.157854,0.030987,0.101192,0.111774,0.147497,0.173821,0.099808,0.115573,...,0.119518,0.197589,0.113135,0.136490,0.162921,0.099021,0.086653,0.158176,0.166968,0.048967

In [ ]:
%%time
min_ = arr.min(axis=0)
max_ = arr.max(axis=0)
min_, max_ = dask.compute(min_, max_)
pd.DataFrame([min_, max_], columns=['e' + str(i) for i in range(312)], index=['min', 'max'])

Wall time: 876 ms

,e0,e1,e2,e3,e4,e5,e6,e7,e8,e9,...,e302,e303,e304,e305,e306,e307,e308,e309,e310,e311
min,-0.132803,-0.149056,-0.094468,-0.191697,-0.114229,-0.114341,-0.096039,-0.115178,-0.157275,-0.116715,...,-0.103254,-0.122285,-0.149789,-0.127703,-0.094802,-0.119690,-0.141425,-0.123732,-0.081543,-0.227348
max,0.135038,0.076125,0.157854,0.030987,0.101192,0.111774,0.147497,0.173821,0.099808,0.115573,...,0.119518,0.197589,0.113135,0.136490,0.162921,0.099021,0.086653,0.158176,0.166968,0.048967

<p class="task" id="4"></p>

4\. Датасет `embeddings` представляет собой набор 312-мерных векторов $x_i, i=0, 1, ... M-1$ Найдите вектор $x \ne x_{256}$ из набора данных, ближайший к вектору $x_{256}$ в смысле метрики $L_1$. Выведите на экран первые 10 координат вектора $x$.

$$d_1(\textbf{x},\textbf{y})=\sum_{k=1}^{n}{|x_i - y_i|}, \textbf{x}, \textbf{y} \in \mathbb{R}^n$$

In [ ]:
arr_ = (abs(arr.copy() - arr[256])).sum(axis=1)
arr_ = arr_[arr_.nonzero()]
arr_.compute_chunk_sizes()
x = arr[arr_.argmin() + 1 if arr_.argmin() >= 256 else arr_.argmin()]
x.compute()[:10]

C:\ProgramData\Anaconda3\lib\site-packages\dask\array\slicing.py:1076: PerformanceWarning: Increasing number of chunks by factor of 12
  p = blockwise(

array([ 0.0331987 , -0.03648246,  0.06629294, -0.0850755 , -0.04708353,
        0.00130241,  0.00259956,  0.01916818, -0.00985817, -0.04410348],
      dtype=float32)

<p class="task" id="5"></p>

5\. Рецепты разбиты на 4 группы. Загрузите маску для разбиения на группы из датасета `mask` из файла `recipe_embeddings.h5` в виде `dask.array`. Для каждой группы посчитайте и выведите на экран максимальное значение нормы $\ell_1$ векторов рецептов, принадлежащих к этой группе.

Подсказка: закодируйте маску принадлежности к группе при помощи метода кодирования one-hot encoding и воспользуйтесь механизмом распространения.

$$\ell_1: ||\textbf{x}||_1=\sum_{k=1}^{n}{|x_k|}, \textbf{x} \in \mathbb{R}^n$$

In [ ]:
mask = da.from_array(fp['mask']).reshape(1, 1200000)
mask_onehot = da.concatenate([mask == 0, mask == 1, mask == 2, mask == 3], axis=0)
mask_onehot

dask.array<concatenate, shape=(4, 1200000), dtype=bool, chunksize=(1, 1200000), chunktype=numpy.ndarray>

In [ ]:
max_l1_0 = (abs(arr[mask_onehot[0]])).sum(axis=1).max()
max_l1_1 = (abs(arr[mask_onehot[1]])).sum(axis=1).max()
max_l1_2 = (abs(arr[mask_onehot[2]])).sum(axis=1).max()
max_l1_3 = (abs(arr[mask_onehot[3]])).sum(axis=1).max()
dask.compute(max_l1_0, max_l1_1, max_l1_2, max_l1_3)

(13.319677, 13.324095, 13.31526, 13.319157)

<p class="task" id="6"></p>

6\. Работая с исходным файлом в формате `hdf`, реализуйте алгоритм подсчета среднего вектора датасета в блочной форме.

Блочный алгоритм вычислений состоит из двух частей:
1. Загрузка фрагмента за фрагментом данных и проведение вычислений над этим фрагментом
2. Агрегация результатов вычислений на различных фрагментах для получения результата на уровне всего набора данных

Важно: при работе с `hdf` в память загружаются не все элементы, а только те, которые запрашиваются в данный момент. При работе с `hdf` вы можете работать с массивами `numpy.array`. Для итерации по сегментам файла допускается использование циклов.

In [ ]:
embeddings = fp['embeddings']

In [ ]:
%%time
means = np.zeros((4, 312), dtype='float64')
for i, chunk in enumerate(np.array_split(embeddings, 4)):
    means[i] = chunk.mean(axis=0, dtype='float64') # вычисления для фрагмента
np.mean(means, axis=0, dtype='float64') # агрегация

Wall time: 1.06 s

array([ 9.75611741e-04, -3.39259919e-02,  4.66551852e-02, -8.74479048e-02,
       -9.71177284e-03,  5.51533102e-03,  2.71454279e-02,  3.75371801e-02,
       -2.35138376e-02, -1.10451345e-02,  2.61558130e-02,  8.86423980e-03,
        1.82164863e-02,  5.94255701e-02,  2.72058591e-02, -6.64570912e-03,
        3.04659187e-02,  1.03974861e-02,  1.93780558e-02,  1.43449808e-01,
       -2.46166348e-03, -5.94153239e-03, -3.18063951e-02, -4.10590974e-02,
        8.61882476e-02,  2.80386887e-02, -2.43214341e-02, -4.59721306e-03,
        1.09600983e-02,  3.78382257e-02, -1.06729240e-02, -1.57453825e-02,
        1.08159234e-03, -2.18519443e-02,  7.02830462e-03,  5.17747034e-02,
       -9.01944597e-04, -3.80986348e-02, -7.50486232e-02,  1.78839388e-02,
       -6.01361417e-02,  1.52847686e-01,  7.50525002e-02, -3.78862367e-02,
       -2.17200478e-02,  3.46801956e-03,  3.78258063e-02, -4.40569770e-02,
        4.40716660e-02, -3.56614161e-02,  8.02603242e-03, -3.51645609e-02,
       -4.23886347e-02,  3.61052133e-02, -9.72662509e-02,  4.22165901e-02,
        5.11279647e-02,  2.77048920e-02,  1.27401244e-02,  1.85521604e-02,
        4.57120444e-02,  4.31890321e-02,  9.40933472e-03,  5.38806366e-02,
        2.11637789e-02,  9.79874686e-02,  1.36365798e-03, -9.18731706e-03,
        7.75334674e-03,  3.38335658e-03,  3.52879245e-02,  9.35993990e-03,
       -3.27013716e-02, -8.93248285e-02, -8.47529195e-03, -4.95786305e-02,
       -1.22359173e-02, -3.75288926e-02,  2.75824006e-02,  3.82324826e-02,
       -6.02782553e-03,  6.43512669e-03, -5.27551391e-02,  3.59735985e-02,
       -3.34230099e-03,  2.72827104e-02, -5.24309750e-03,  1.64817953e-02,
        2.25580926e-02, -2.09053977e-02,  7.71984934e-02,  6.49010361e-02,
        7.99613204e-02,  7.90071337e-03, -1.12463179e-02, -2.40223845e-02,
        4.26060017e-02,  7.46190611e-03, -1.49448339e-02,  2.72488965e-02,
       -1.59145948e-02,  2.88091781e-02,  3.00883842e-02, -2.48277038e-02,
       -1.89418552e-02, -2.75628887e-02,  9.94008386e-03, -4.11241417e-03,
       -3.53858910e-02, -1.60155980e-02, -6.81685547e-02,  4.96624218e-03,
        8.47199021e-02,  4.98796118e-02,  2.81187453e-02,  4.07871615e-02,
       -9.65413215e-02,  1.60226680e-02,  2.47696507e-02, -6.45706452e-02,
        3.82247782e-02, -4.43642678e-02, -2.37735847e-02,  6.38587324e-03,
       -6.29339023e-02, -1.47310929e-02,  5.12773082e-02, -1.11327902e-02,
       -6.71471709e-03,  6.84353097e-03, -2.63280965e-02, -2.91614028e-02,
        4.15657603e-02, -1.75915526e-02,  2.11374306e-02,  3.97521336e-04,
       -2.34398476e-02,  1.27416718e-03,  5.03011058e-02, -1.41903540e-03,
        2.90012509e-02, -1.23919987e-01,  4.18265624e-02,  2.08072052e-02,
       -1.53482404e-02, -4.25928023e-02, -6.50814306e-02,  2.16929869e-02,
        3.25728140e-02,  4.92711880e-02,  1.27108182e-02, -3.71227672e-02,
       -4.40062915e-02, -5.49684365e-02,  3.71041023e-02,  1.99102014e-02,
       -1.47375145e-02,  8.11743484e-02,  6.48534527e-02,  5.05882978e-02,
        4.55739708e-02, -1.37275179e-02,  5.93503015e-02, -9.72069158e-02,
       -6.67069221e-03,  8.16483490e-03,  1.10985297e-02,  1.44168346e-02,
       -1.12628182e-02, -1.19114796e-02, -2.72192971e-04,  1.68723994e-02,
        8.37172025e-03,  1.18742352e-02,  4.11335208e-02,  4.76576809e-02,
        3.15732911e-02, -6.32962487e-03, -8.18583410e-03, -8.89194367e-03,
        7.04177366e-02, -1.64567151e-02,  7.80395905e-02, -3.14686657e-02,
        7.00759240e-02,  2.12508789e-02, -6.06228793e-03, -1.12460734e-02,
        1.40455389e-02,  4.88088454e-02,  7.75098338e-03, -1.53937064e-02,
       -6.21984079e-02,  8.96287652e-03,  9.20574445e-02, -5.29912019e-01,
        3.48530852e-02,  5.30005714e-02,  4.83882880e-02, -1.15462670e-02,
       -9.77664361e-03,  1.44908553e-02, -1.22740532e-02, -1.96601439e-03,
       -6.69926342e-02,  1.71923538e-02,  1.24684089e-03, -1.50180946e-02,
        3.86962639e-02, -2.20223377e-02, -1.32592230e-03, -1.07632925e-02,
        3.53816897e-02,  8.61474389e-02, -3.80215830e-03, -3.93439715e-02,
        2.08743782e-02, -6.80792805e-04,  8.79222609e-03,  1.50819996e-02,
       -1.75768900e-02,  2.47568165e-02,  1.63916464e-02,  8.95599641e-03,
       -3.76104386e-03, -2.11225904e-02, -3.47931218e-02,  2.13235080e-02,
       -9.71844981e-03,  2.55059385e-03, -2.43566639e-02, -2.09987396e-03,
       -2.09617253e-02, -1.92961754e-02, -8.63745502e-03,  3.17218913e-02,
        5.67122488e-02, -4.80271488e-02,  5.50537094e-03, -1.17691546e-02,
       -1.95940528e-02,  3.70259785e-02, -2.18715971e-02, -1.62057405e-02,
       -7.61052111e-04,  8.07679973e-04, -1.03023507e-03,  3.09864255e-02,
       -1.99379131e-02, -1.12921993e-02, -4.55267624e-04,  1.24688692e-02,
       -6.04161486e-02, -9.40528631e-02, -1.56641266e-02, -7.09190059e-03,
       -2.45840596e-02, -4.36269815e-03, -2.20897550e-02,  1.39252721e-02,
        5.61719767e-02,  4.51656546e-02, -3.85405675e-03,  1.09189883e-02,
       -9.77814936e-02,  4.80061865e-02, -4.49278777e-02, -1.77840026e-02,
        5.26250859e-02, -4.27060347e-05,  1.71298278e-02,  3.33909561e-02,
       -1.89228536e-02,  6.23040825e-02,  2.17257743e-02,  1.26852054e-02,
        9.94409429e-03, -3.65873952e-02,  2.48322707e-02, -8.13882669e-03,
        8.07021449e-02, -6.92804473e-03, -5.17849325e-02,  6.76394118e-02,
        5.62964198e-03,  1.53569433e-02, -2.93501389e-02,  2.75426525e-03,
       -5.19041128e-03, -5.43002032e-02, -8.58054798e-03,  1.49922296e-02,
        6.24008894e-03, -4.21790024e-02, -3.01857727e-02,  9.03212106e-02,
       -3.77552331e-02,  2.81668795e-02,  6.69795640e-03, -5.48122184e-02,
        6.39849792e-03, -1.16621582e-02,  1.93224490e-02,  5.02772170e-02,
       -1.83763544e-02,  1.45910299e-02,  2.97320209e-02,  3.31390653e-03,
       -3.47341262e-02,  2.00876010e-02,  4.44885832e-02, -1.07661915e-01])

<p class="task" id="7"></p>

7\. Решите задачу 6, распараллелив вычисления при помощи `ThreadPool`. Сравните время и результаты решения работы вашего алгоритма с реализацией поиска среднего вектора из `dask`.

In [ ]:
from multiprocessing.pool import ThreadPool

In [ ]:
%%time
embeddings_split = np.array_split(embeddings, 4)
with ThreadPool(processes = 4) as pool:
    r = pool.map(lambda x: np.mean(x, axis=0, dtype='float64'), embeddings_split)
np.mean(r, axis=0, dtype='float64')

Wall time: 754 ms

array([ 9.75611741e-04, -3.39259919e-02,  4.66551852e-02, -8.74479048e-02,
       -9.71177284e-03,  5.51533102e-03,  2.71454279e-02,  3.75371801e-02,
       -2.35138376e-02, -1.10451345e-02,  2.61558130e-02,  8.86423980e-03,
        1.82164863e-02,  5.94255701e-02,  2.72058591e-02, -6.64570912e-03,
        3.04659187e-02,  1.03974861e-02,  1.93780558e-02,  1.43449808e-01,
       -2.46166348e-03, -5.94153239e-03, -3.18063951e-02, -4.10590974e-02,
        8.61882476e-02,  2.80386887e-02, -2.43214341e-02, -4.59721306e-03,
        1.09600983e-02,  3.78382257e-02, -1.06729240e-02, -1.57453825e-02,
        1.08159234e-03, -2.18519443e-02,  7.02830462e-03,  5.17747034e-02,
       -9.01944597e-04, -3.80986348e-02, -7.50486232e-02,  1.78839388e-02,
       -6.01361417e-02,  1.52847686e-01,  7.50525002e-02, -3.78862367e-02,
       -2.17200478e-02,  3.46801956e-03,  3.78258063e-02, -4.40569770e-02,
        4.40716660e-02, -3.56614161e-02,  8.02603242e-03, -3.51645609e-02,
       -4.23886347e-02,  3.61052133e-02, -9.72662509e-02,  4.22165901e-02,
        5.11279647e-02,  2.77048920e-02,  1.27401244e-02,  1.85521604e-02,
        4.57120444e-02,  4.31890321e-02,  9.40933472e-03,  5.38806366e-02,
        2.11637789e-02,  9.79874686e-02,  1.36365798e-03, -9.18731706e-03,
        7.75334674e-03,  3.38335658e-03,  3.52879245e-02,  9.35993990e-03,
       -3.27013716e-02, -8.93248285e-02, -8.47529195e-03, -4.95786305e-02,
       -1.22359173e-02, -3.75288926e-02,  2.75824006e-02,  3.82324826e-02,
       -6.02782553e-03,  6.43512669e-03, -5.27551391e-02,  3.59735985e-02,
       -3.34230099e-03,  2.72827104e-02, -5.24309750e-03,  1.64817953e-02,
        2.25580926e-02, -2.09053977e-02,  7.71984934e-02,  6.49010361e-02,
        7.99613204e-02,  7.90071337e-03, -1.12463179e-02, -2.40223845e-02,
        4.26060017e-02,  7.46190611e-03, -1.49448339e-02,  2.72488965e-02,
       -1.59145948e-02,  2.88091781e-02,  3.00883842e-02, -2.48277038e-02,
       -1.89418552e-02, -2.75628887e-02,  9.94008386e-03, -4.11241417e-03,
       -3.53858910e-02, -1.60155980e-02, -6.81685547e-02,  4.96624218e-03,
        8.47199021e-02,  4.98796118e-02,  2.81187453e-02,  4.07871615e-02,
       -9.65413215e-02,  1.60226680e-02,  2.47696507e-02, -6.45706452e-02,
        3.82247782e-02, -4.43642678e-02, -2.37735847e-02,  6.38587324e-03,
       -6.29339023e-02, -1.47310929e-02,  5.12773082e-02, -1.11327902e-02,
       -6.71471709e-03,  6.84353097e-03, -2.63280965e-02, -2.91614028e-02,
        4.15657603e-02, -1.75915526e-02,  2.11374306e-02,  3.97521336e-04,
       -2.34398476e-02,  1.27416718e-03,  5.03011058e-02, -1.41903540e-03,
        2.90012509e-02, -1.23919987e-01,  4.18265624e-02,  2.08072052e-02,
       -1.53482404e-02, -4.25928023e-02, -6.50814306e-02,  2.16929869e-02,
        3.25728140e-02,  4.92711880e-02,  1.27108182e-02, -3.71227672e-02,
       -4.40062915e-02, -5.49684365e-02,  3.71041023e-02,  1.99102014e-02,
       -1.47375145e-02,  8.11743484e-02,  6.48534527e-02,  5.05882978e-02,
        4.55739708e-02, -1.37275179e-02,  5.93503015e-02, -9.72069158e-02,
       -6.67069221e-03,  8.16483490e-03,  1.10985297e-02,  1.44168346e-02,
       -1.12628182e-02, -1.19114796e-02, -2.72192971e-04,  1.68723994e-02,
        8.37172025e-03,  1.18742352e-02,  4.11335208e-02,  4.76576809e-02,
        3.15732911e-02, -6.32962487e-03, -8.18583410e-03, -8.89194367e-03,
        7.04177366e-02, -1.64567151e-02,  7.80395905e-02, -3.14686657e-02,
        7.00759240e-02,  2.12508789e-02, -6.06228793e-03, -1.12460734e-02,
        1.40455389e-02,  4.88088454e-02,  7.75098338e-03, -1.53937064e-02,
       -6.21984079e-02,  8.96287652e-03,  9.20574445e-02, -5.29912019e-01,
        3.48530852e-02,  5.30005714e-02,  4.83882880e-02, -1.15462670e-02,
       -9.77664361e-03,  1.44908553e-02, -1.22740532e-02, -1.96601439e-03,
       -6.69926342e-02,  1.71923538e-02,  1.24684089e-03, -1.50180946e-02,
        3.86962639e-02, -2.20223377e-02, -1.32592230e-03, -1.07632925e-02,
        3.53816897e-02,  8.61474389e-02, -3.80215830e-03, -3.93439715e-02,
        2.08743782e-02, -6.80792805e-04,  8.79222609e-03,  1.50819996e-02,
       -1.75768900e-02,  2.47568165e-02,  1.63916464e-02,  8.95599641e-03,
       -3.76104386e-03, -2.11225904e-02, -3.47931218e-02,  2.13235080e-02,
       -9.71844981e-03,  2.55059385e-03, -2.43566639e-02, -2.09987396e-03,
       -2.09617253e-02, -1.92961754e-02, -8.63745502e-03,  3.17218913e-02,
        5.67122488e-02, -4.80271488e-02,  5.50537094e-03, -1.17691546e-02,
       -1.95940528e-02,  3.70259785e-02, -2.18715971e-02, -1.62057405e-02,
       -7.61052111e-04,  8.07679973e-04, -1.03023507e-03,  3.09864255e-02,
       -1.99379131e-02, -1.12921993e-02, -4.55267624e-04,  1.24688692e-02,
       -6.04161486e-02, -9.40528631e-02, -1.56641266e-02, -7.09190059e-03,
       -2.45840596e-02, -4.36269815e-03, -2.20897550e-02,  1.39252721e-02,
        5.61719767e-02,  4.51656546e-02, -3.85405675e-03,  1.09189883e-02,
       -9.77814936e-02,  4.80061865e-02, -4.49278777e-02, -1.77840026e-02,
        5.26250859e-02, -4.27060347e-05,  1.71298278e-02,  3.33909561e-02,
       -1.89228536e-02,  6.23040825e-02,  2.17257743e-02,  1.26852054e-02,
        9.94409429e-03, -3.65873952e-02,  2.48322707e-02, -8.13882669e-03,
        8.07021449e-02, -6.92804473e-03, -5.17849325e-02,  6.76394118e-02,
        5.62964198e-03,  1.53569433e-02, -2.93501389e-02,  2.75426525e-03,
       -5.19041128e-03, -5.43002032e-02, -8.58054798e-03,  1.49922296e-02,
        6.24008894e-03, -4.21790024e-02, -3.01857727e-02,  9.03212106e-02,
       -3.77552331e-02,  2.81668795e-02,  6.69795640e-03, -5.48122184e-02,
        6.39849792e-03, -1.16621582e-02,  1.93224490e-02,  5.02772170e-02,
       -1.83763544e-02,  1.45910299e-02,  2.97320209e-02,  3.31390653e-03,
       -3.47341262e-02,  2.00876010e-02,  4.44885832e-02, -1.07661915e-01])

In [ ]:
%%time
embeddings_da = da.from_array(embeddings)
embeddings_da.mean(axis=0, dtype='float64').compute()

Wall time: 744 ms

array([ 9.75611741e-04, -3.39259919e-02,  4.66551852e-02, -8.74479048e-02,
       -9.71177284e-03,  5.51533102e-03,  2.71454279e-02,  3.75371801e-02,
       -2.35138376e-02, -1.10451345e-02,  2.61558130e-02,  8.86423980e-03,
        1.82164863e-02,  5.94255701e-02,  2.72058591e-02, -6.64570912e-03,
        3.04659187e-02,  1.03974861e-02,  1.93780558e-02,  1.43449808e-01,
       -2.46166348e-03, -5.94153239e-03, -3.18063951e-02, -4.10590974e-02,
        8.61882476e-02,  2.80386887e-02, -2.43214341e-02, -4.59721306e-03,
        1.09600983e-02,  3.78382257e-02, -1.06729240e-02, -1.57453825e-02,
        1.08159234e-03, -2.18519443e-02,  7.02830462e-03,  5.17747034e-02,
       -9.01944597e-04, -3.80986348e-02, -7.50486232e-02,  1.78839388e-02,
       -6.01361417e-02,  1.52847686e-01,  7.50525002e-02, -3.78862367e-02,
       -2.17200478e-02,  3.46801956e-03,  3.78258063e-02, -4.40569770e-02,
        4.40716660e-02, -3.56614161e-02,  8.02603242e-03, -3.51645609e-02,
       -4.23886347e-02,  3.61052133e-02, -9.72662509e-02,  4.22165901e-02,
        5.11279647e-02,  2.77048920e-02,  1.27401244e-02,  1.85521604e-02,
        4.57120444e-02,  4.31890321e-02,  9.40933472e-03,  5.38806366e-02,
        2.11637789e-02,  9.79874686e-02,  1.36365798e-03, -9.18731706e-03,
        7.75334674e-03,  3.38335658e-03,  3.52879245e-02,  9.35993990e-03,
       -3.27013716e-02, -8.93248285e-02, -8.47529195e-03, -4.95786305e-02,
       -1.22359173e-02, -3.75288926e-02,  2.75824006e-02,  3.82324826e-02,
       -6.02782553e-03,  6.43512669e-03, -5.27551391e-02,  3.59735985e-02,
       -3.34230099e-03,  2.72827104e-02, -5.24309750e-03,  1.64817953e-02,
        2.25580926e-02, -2.09053977e-02,  7.71984934e-02,  6.49010361e-02,
        7.99613204e-02,  7.90071337e-03, -1.12463179e-02, -2.40223845e-02,
        4.26060017e-02,  7.46190611e-03, -1.49448339e-02,  2.72488965e-02,
       -1.59145948e-02,  2.88091781e-02,  3.00883842e-02, -2.48277038e-02,
       -1.89418552e-02, -2.75628887e-02,  9.94008386e-03, -4.11241417e-03,
       -3.53858910e-02, -1.60155980e-02, -6.81685547e-02,  4.96624218e-03,
        8.47199021e-02,  4.98796118e-02,  2.81187453e-02,  4.07871615e-02,
       -9.65413215e-02,  1.60226680e-02,  2.47696507e-02, -6.45706452e-02,
        3.82247782e-02, -4.43642678e-02, -2.37735847e-02,  6.38587324e-03,
       -6.29339023e-02, -1.47310929e-02,  5.12773082e-02, -1.11327902e-02,
       -6.71471709e-03,  6.84353097e-03, -2.63280965e-02, -2.91614028e-02,
        4.15657603e-02, -1.75915526e-02,  2.11374306e-02,  3.97521336e-04,
       -2.34398476e-02,  1.27416718e-03,  5.03011058e-02, -1.41903540e-03,
        2.90012509e-02, -1.23919987e-01,  4.18265624e-02,  2.08072052e-02,
       -1.53482404e-02, -4.25928023e-02, -6.50814306e-02,  2.16929869e-02,
        3.25728140e-02,  4.92711880e-02,  1.27108182e-02, -3.71227672e-02,
       -4.40062915e-02, -5.49684365e-02,  3.71041023e-02,  1.99102014e-02,
       -1.47375145e-02,  8.11743484e-02,  6.48534527e-02,  5.05882978e-02,
        4.55739708e-02, -1.37275179e-02,  5.93503015e-02, -9.72069158e-02,
       -6.67069221e-03,  8.16483490e-03,  1.10985297e-02,  1.44168346e-02,
       -1.12628182e-02, -1.19114796e-02, -2.72192971e-04,  1.68723994e-02,
        8.37172025e-03,  1.18742352e-02,  4.11335208e-02,  4.76576809e-02,
        3.15732911e-02, -6.32962487e-03, -8.18583410e-03, -8.89194367e-03,
        7.04177366e-02, -1.64567151e-02,  7.80395905e-02, -3.14686657e-02,
        7.00759240e-02,  2.12508789e-02, -6.06228793e-03, -1.12460734e-02,
        1.40455389e-02,  4.88088454e-02,  7.75098338e-03, -1.53937064e-02,
       -6.21984079e-02,  8.96287652e-03,  9.20574445e-02, -5.29912019e-01,
        3.48530852e-02,  5.30005714e-02,  4.83882880e-02, -1.15462670e-02,
       -9.77664361e-03,  1.44908553e-02, -1.22740532e-02, -1.96601439e-03,
       -6.69926342e-02,  1.71923538e-02,  1.24684089e-03, -1.50180946e-02,
        3.86962639e-02, -2.20223377e-02, -1.32592230e-03, -1.07632925e-02,
        3.53816897e-02,  8.61474389e-02, -3.80215830e-03, -3.93439715e-02,
        2.08743782e-02, -6.80792805e-04,  8.79222609e-03,  1.50819996e-02,
       -1.75768900e-02,  2.47568165e-02,  1.63916464e-02,  8.95599641e-03,
       -3.76104386e-03, -2.11225904e-02, -3.47931218e-02,  2.13235080e-02,
       -9.71844981e-03,  2.55059385e-03, -2.43566639e-02, -2.09987396e-03,
       -2.09617253e-02, -1.92961754e-02, -8.63745502e-03,  3.17218913e-02,
        5.67122488e-02, -4.80271488e-02,  5.50537094e-03, -1.17691546e-02,
       -1.95940528e-02,  3.70259785e-02, -2.18715971e-02, -1.62057405e-02,
       -7.61052111e-04,  8.07679973e-04, -1.03023507e-03,  3.09864255e-02,
       -1.99379131e-02, -1.12921993e-02, -4.55267624e-04,  1.24688692e-02,
       -6.04161486e-02, -9.40528631e-02, -1.56641266e-02, -7.09190059e-03,
       -2.45840596e-02, -4.36269815e-03, -2.20897550e-02,  1.39252721e-02,
        5.61719767e-02,  4.51656546e-02, -3.85405675e-03,  1.09189883e-02,
       -9.77814936e-02,  4.80061865e-02, -4.49278777e-02, -1.77840026e-02,
        5.26250859e-02, -4.27060347e-05,  1.71298278e-02,  3.33909561e-02,
       -1.89228536e-02,  6.23040825e-02,  2.17257743e-02,  1.26852054e-02,
        9.94409429e-03, -3.65873952e-02,  2.48322707e-02, -8.13882669e-03,
        8.07021449e-02, -6.92804473e-03, -5.17849325e-02,  6.76394118e-02,
        5.62964198e-03,  1.53569433e-02, -2.93501389e-02,  2.75426525e-03,
       -5.19041128e-03, -5.43002032e-02, -8.58054798e-03,  1.49922296e-02,
        6.24008894e-03, -4.21790024e-02, -3.01857727e-02,  9.03212106e-02,
       -3.77552331e-02,  2.81668795e-02,  6.69795640e-03, -5.48122184e-02,
        6.39849792e-03, -1.16621582e-02,  1.93224490e-02,  5.02772170e-02,
       -1.83763544e-02,  1.45910299e-02,  2.97320209e-02,  3.31390653e-03,
       -3.47341262e-02,  2.00876010e-02,  4.44885832e-02, -1.07661915e-01])